<form method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getAttrib('id');?>" class="<?php echo $this->element->getAttrib('class');?>"  enctype="<?php echo $this->element->getEncType();?>">
<table class="tableAdmin box-tbl-info" width="630" cellpadding="0" cellspacing="0" border="0">
    <col width="200" />
    <tr>
        <th valign="middle">
            <?php
            $attribs = array();
            if ($this->element->code->isRequired()) {
                $attribs['class'] = 'required';
            }
            echo $this->formLabel($this->element->code->getName(), $this->element->code->getLabel(), $attribs);?>
        </th>
        <td>
            <?php
                echo $this->{$this->element->code->helper}(
                            $this->element->code->getName(),
                            $this->element->code->getValue(),
                            $this->element->code->getAttribs()
                        );
            ?>
            <?php if('<ul class="errors"><li></li></ul>'!=($this->element->code->getMessages())){ echo  $this->formErrors($this->element->code->getMessages());} ?>
        </td>
    </tr>
    <tr>
    <tr>
        <th valign="middle">&nbsp;</th>
        <td>
            <?php echo $this->{$this->element->submit->helper}(
                            $this->element->submit->getName(),
                            $this->element->submit->getValue(),
                            $this->element->submit->getAttribs()
                        );
            ?>
        </td>
    </tr>
</table>
</form>
<script type="text/javascript">
$(document).ready(function() {
    $("#<?php echo $this->element->getAttrib('id');?>").validationEngine();
});
</script>