<form method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction(); ?>"
      id="<?php echo $this->element->getAttrib('id'); ?>" class="<?php echo $this->element->getAttrib('class'); ?>"
      enctype="<?php echo $this->element->getEncType(); ?>">
    <table class="tableAdmin box-tbl-info" width="630" cellpadding="0" cellspacing="0" border="0">
        <col width="200"/>
        <tr>
            <th valign="middle">
                <?php
                $attribs = array();
                if ($this->element->name->isRequired()) {
                    $attribs['class'] = 'required';
                }
                echo $this->formLabel($this->element->name->getName(), $this->element->name->getLabel(), $attribs); ?>
            </th>
            <td>
                <?php
                echo $this->{$this->element->name->helper}(
                    $this->element->name->getName(),
                    $this->element->name->getValue(),
                    $this->element->name->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->element->name->getMessages())) {
                    echo $this->formErrors($this->element->name->getMessages());
                } ?>
                <div class="hint"><?php echo $this->element->name->getDescription(); ?></div>
            </td>
        </tr>
        <tr>
            <th valign="middle">
                <?php
                $attribs = array();
                if ($this->element->parentId->isRequired()) {
                    $attribs['class'] = 'required';
                }
                echo $this->formLabel($this->element->name->getName(), $this->element->parentId->getLabel(), $attribs); ?>
            </th>
            <td>
                <?php
                echo $this->{$this->element->parentId->helper}(
                    $this->element->parentId->getName(),
                    $this->element->parentId->getValue(),
                    $this->element->parentId->getAttribs(),
                    $this->element->parentId->getMultiOptions(),
                    '&nbsp;&nbsp;&nbsp;'
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->element->parentId->getMessages())) {
                    echo $this->formErrors($this->element->parentId->getMessages());
                } ?>
                <div class="hint"><?php echo $this->element->parentId->getDescription(); ?></div>
            </td>
        </tr>
        <tr>
            <th valign="middle">&nbsp;</th>
            <td>
                <?php echo $this->{$this->element->submit->helper}(
                    $this->element->submit->getName(),
                    $this->element->submit->getValue(),
                    $this->element->submit->getAttribs()
                );
                ?>
            </td>
        </tr>
    </table>
</form>
<script type="text/javascript">
    $(document).ready(function () {
        $("#<?php echo $this->element->getAttrib('id');?>").validationEngine();
    });
</script>