<?php if (!empty($this->message)) : ?>
    <?php foreach ($this->message as $value) : ?>
        <div class="empty10"></div>
        <?php echo $value; ?>
    <?php endforeach; ?>
<?php endif; ?>

<?php if (null != $this->result) { ?>
    <div class="empty10"></div>
    <table class="tableListingsAll" width="100%" cellspacing="0" cellpadding="0" border="0">
        <col width=""/>
        <col width="80"/>
        <tr>
            <th>Cod</th>
            <th>Status</th>
            <th>Optiuni</th>
        </tr>
        <?php foreach ($this->result as $value) { ?>
            <tr>
                <td><?php echo $value->getCode(); ?></td>
                <td><?php echo $value->getStatus(); ?></td>
                <td align="center">
                    <a href="/admin/coupon/<?php if ($value->getStatus() == 'active') {
                        echo 'dezactivate';
                    } else {
                        echo 'activate';
                    } ?>/id/<?php echo $value->getId(); ?>" title="<?php if ($value->getStatus() == 'active') {
                        echo 'Dezactivare';
                    } else {
                        echo 'Activare';
                    } ?>">
                        <?php if ($value->getStatus() == 'active') {
                            echo 'Dezactivare';
                        } else {
                            echo 'Activare';
                        } ?>
                    </a>
                    <a href="/admin/coupon/edit/id/<?php echo $value->getId(); ?>" title="Modifica">
                        <img src="/images/admin/icons/edit.png" alt="modifica"/>
                    </a>
                    <a class="confirmDelete" href="/admin/coupon/delete/id/<?php echo $value->getId(); ?>"
                       title="Sterge">
                        <img src="/images/admin/icons/delete.png" alt="sterge"/>
                    </a>
                </td>
            </tr>
        <?php } ?>
    </table>
    <div id="confirmDelete" title="<?php echo Zend_Registry::get('translate')->_('confirmation_message'); ?>"
         style="display:none;">
        Sunteţi sigur că doriţi să ştergeţi acest cupon?
    </div>
<?php } else { ?>
    <div class="empty10"></div>
    <div class="mess-false">Nu exista cupoane!</div>
<?php } ?>

<script type="text/javascript">
    $(document).ready(function () {
        $('.confirmDelete').click(function () {
            var link = $(this);
            $("#confirmDelete").dialog({
                bgiframe: true,
                height: 140,
                width: 400,
                modal: true,
                buttons: {
                    '<?php echo Zend_Registry::get('translate')->_('confirmation_yes'); ?>': function () {
                        $(this).dialog('close').dialog('destroy');
                        window.location.href = link.attr('href');
                    },
                    '<?php echo Zend_Registry::get('translate')->_('confirmation_no'); ?>': function () {
                        $(this).dialog('close').dialog('destroy');
                    }
                }
            });
            return false;
        });
    });
</script>