<form method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction(); ?>"
      id="<?php echo $this->element->getId(); ?>" enctype="<?php echo $this->element->getEncType(); ?>">
    <div class="regSubForm">
        <h3 class="expandable"><?php echo Zend_Registry::get('translate')->_("cms_add_page_title_page_information"); ?></h3>
        <table width="100%" cellpadding="0" cellspacing="5" class="tableAdmin">
            <col width="200"/>
            <tr>
                <td valign="top">
                    <?php
                    $attribs = array();
                    if ($this->element->headline->isRequired()) {
                        $attribs['class'] = 'required';
                    }
                    echo $this->formLabel($this->element->headline->getName(), $this->element->headline->getLabel(), $attribs); ?>
                </td>
                <td>
                    <?php
                    echo $this->{$this->element->headline->helper}(
                        $this->element->headline->getName(),
                        $this->element->headline->getValue(),
                        $this->element->headline->getAttribs()
                    );
                    ?>
                    <?php if ('<ul class="errors"><li></li></ul>' != ($this->formErrors($this->element->headline->getMessages()))) {
                        echo $this->formErrors($this->element->headline->getMessages());
                    } ?>
                    <p class="description"><?php echo $this->element->headline->getDescription() ?></p>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <?php
                    echo $this->{$this->element->content->helper}(
                        $this->element->content->getName(),
                        $this->element->content->getValue(),
                        $this->element->content->getAttribs()
                    );
                    ?>
                    <?php if ('<ul class="errors"><li></li></ul>' != ($this->formErrors($this->element->content->getMessages()))) {
                        echo $this->formErrors($this->element->content->getMessages());
                    } ?>
                    <p class="description"><?php echo $this->element->content->getDescription() ?></p>
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td valign="top">
                    &nbsp;
                </td>
                <td>
                    <?php
                    echo $this->{$this->element->submit->helper}(
                        $this->element->submit->getName(),
                        $this->element->submit->getValue(),
                        $this->element->submit->getAttribs()
                    );
                    ?>
                </td>
            </tr>
        </table>
    </div>
</form>

<?php
$this->headScript()->appendFile('/js/ckeditor/ckeditor.js');
echo $this->headScript();
?>
<?php $this->headScript()->captureStart() ?>
$(document).ready(function() {
<!--		CKEDITOR.replace( 'content',
			{
				width: '800',
				height: '400'
			}
		);-->

$("#<?php echo $this->element->getAttrib('id'); ?>").validationEngine();
});
<?php $this->headScript()->captureEnd() ?>