<form class="login-form" method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getId();?>" enctype="<?php echo $this->element->getEncType();?>">
	<div class="loginBox2">
		<!--BEGIN:USERNAME-->
		<?php
			echo $this->formLabel($this->element->username->getName(), $this->element->username->getLabel());
	   ?>
		<?php
			echo $this->{$this->element->username->helper}(
						$this->element->username->getName(),
						$this->element->username->getValue(),
						$this->element->username->getAttribs()
					);
		?>
		<?php if($this->element->username->getMessages() != array()) : ?>
			<?php echo $this->formErrors($this->element->username->getMessages()) ?>
		<?php endif; ?>
		<?php if ($this->element->username->getDescription()) : ?>
			<p class="description"><?php echo $this->element->username->getDescription() ?></p>
		<?php endif; ?>
		<!--END:USERNAME-->	
		
		<!--BEGIN:Password-->
		<?php
			echo $this->formLabel($this->element->passwordLogare->getName(), $this->element->passwordLogare->getLabel());
	   ?>
		<?php
			echo $this->{$this->element->passwordLogare->helper}(
						$this->element->passwordLogare->getName(),
						$this->element->passwordLogare->getValue(),
						$this->element->passwordLogare->getAttribs()
					);
		?>
		<?php if($this->element->passwordLogare->getMessages() != array()) : ?>
			<?php echo $this->formErrors($this->element->passwordLogare->getMessages()) ?>
		<?php endif; ?>
		<?php if ($this->element->passwordLogare->getDescription()) : ?>
			<p class="description"><?php echo $this->element->passwordLogare->getDescription() ?></p>
		<?php endif; ?>
		<!--END:Password-->	
		

		<div class="clearfix">
			<br />
			<a href="/auth/remind" class="forgottenPass">Forgotten Password</a>
			<?php
			echo $this->{$this->element->submit->helper}(
					$this->element->submit->getName(),
					$this->element->submit->getValue(),
					$this->element->submit->getAttribs()
				);
			?>
		</div>
	</div>
</form>
<script type="text/javascript">
	$(document).ready(function() {
		$("#<?php echo $this->element->getId();?>").validationEngine();
	});
</script>

