<form method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction(); ?>"
      id="<?php echo $this->element->getAttrib('id'); ?>" class="<?php echo $this->element->getAttrib('class'); ?>"
      enctype="<?php echo $this->element->getEncType(); ?>">
    <table width="100%" cellpadding="0" cellspacing="5" class="table">
        <col width="200"/>
        <tr>
            <td valign="top">
                <?php
                $attribs = array();
                if ($this->element->quantity->isRequired()) {
                    $attribs['class'] = 'required';
                }
                echo $this->formLabel($this->element->quantity->getName(), $this->element->quantity->getLabel(), $attribs); ?>
            </td>
            <td>
                <?php
                echo $this->{$this->element->quantity->helper}(
                    $this->element->quantity->getName(),
                    $this->element->quantity->getValue(),
                    $this->element->quantity->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->element->quantity->getMessages())) {
                    echo $this->formErrors($this->element->quantity->getMessages());
                } ?>
                <div class="hint"><?php echo $this->element->quantity->getDescription(); ?></div>
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>
                <?php echo $this->{$this->element->submit->helper}(
                    $this->element->submit->getName(),
                    $this->element->submit->getValue(),
                    $this->element->submit->getAttribs()
                );
                ?>
            </td>
        </tr>
    </table>
</form>
<?php $this->headScript()->captureStart() ?>
$(document).ready(function() {
$("#<?php echo $this->element->getId(); ?>").validationEngine();
});
<?php $this->headScript()->captureEnd() ?>
