<form method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getAttrib('id');?>" class="<?php echo $this->element->getAttrib('class');?>" enctype="<?php echo $this->element->getEncType();?>">
		<td valign="top">
			<?php
			$attribs = array();
			if ($this->element->code->isRequired()) {
				$attribs['class'] = 'required';
			}
			echo $this->formLabel($this->element->code->getName(), $this->element->code->getLabel(), $attribs);?>
		</td>
		<td>
	    	<?php
	    		echo $this->{$this->element->code->helper}(
	    					$this->element->code->getName(),
	    					$this->element->code->getValue(),
	    					$this->element->code->getAttribs()
	    				);
	    	?>
	    	<?php if('<ul class="errors"><li></li></ul>'!=($this->element->code->getMessages())){ echo  $this->formErrors($this->element->code->getMessages());} ?>
			<div class="hint"><?php echo $this->element->code->getDescription(); ?></div>
		</td>
		<td>
	    	<?php echo $this->{$this->element->submit->helper}(
	    					$this->element->submit->getName(),
	    					$this->element->submit->getValue(),
	    					$this->element->submit->getAttribs()
	    				);
	    	?>
		</td>
</form>
<?php $this->headScript()->captureStart() ?>
	$(document).ready(function() {
		$("#<?php echo $this->element->getId();?>").validationEngine();
	});
<?php $this->headScript()->captureEnd() ?>