<div class="box">
	<form method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getId();?>" class="<?php echo $this->element->getAttrib('class');?>" enctype="<?php echo $this->element->getEncType();?>">
		  <table width="100%" cellpadding="0" cellspacing="2" class="cart-delivery-tbl">
		    <col width="200" />
		    <tr>
			<td colspan="2">
			    <small class="hint fR"><?php echo Zend_Registry::get('translate')->_("user_required");?></small>
			</td>
		    </tr>
		</table>
		<h2><?php echo Zend_Registry::get('translate')->_("user_password");?></h2>
		<table width="100%" cellpadding="0" cellspacing="5" class="cart-delivery-tbl">
			<col width="200" />
			<?php
			echo $this->{$this->element->changepass->helper}(
				$this->element->changepass->getName(),
				$this->element->changepass->getValue(),
				$this->element->changepass->getAttribs()
			);
			?>			
			<tr>
				<td>
					<?php
					$attribs = array();
					if ($this->element->oldPassword->isRequired()) {
						$attribs["class"] = array("required");
					}
					echo $this->formLabel($this->element->oldPassword->getName(), $this->element->oldPassword->getLabel(), $attribs) ;
					unset($attribs);
					?>
				</td>
				<td>
					<?php
					echo $this->{$this->element->oldPassword->helper}(
						$this->element->oldPassword->getName(),
						$this->element->oldPassword->getValue(),
						$this->element->oldPassword->getAttribs()
					);
					?>
				</td>
			</tr>
				<tr>
					<td>
						<?php
						$attribs = array();
						if ($this->element->password->isRequired()) {
							$attribs["class"] = array("required");
						}
						echo $this->formLabel($this->element->password->getName(), $this->element->password->getLabel(), $attribs) ;
						unset($attribs);
						?>
					</td>
					<td valign="bottom">
						<?php
						echo $this->{$this->element->password->helper}(
							$this->element->password->getName(),
							$this->element->password->getValue(),
							$this->element->password->getAttribs()
						);
						?>
						<p class="description" style="margin:0px; padding:1px 0 0 0;"><?php echo $this->element->password->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td>
						<?php
						$attribs = array();
						if ($this->element->tbRePassword->isRequired()) {
							$attribs["class"] = array("required");
						}
						echo $this->formLabel($this->element->tbRePassword->getName(), $this->element->tbRePassword->getLabel(), $attribs) ;
						unset($attribs);
						?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->tbRePassword ->helper}(
							$this->element->tbRePassword ->getName(),
							$this->element->tbRePassword ->getValue(),
							$this->element->tbRePassword ->getAttribs()
						);
						?>
					</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>
						<?php
						echo $this->{$this->element->submitPass->helper}(
							$this->element->submitPass->getName(),
							$this->element->submitPass->getValue(),
							$this->element->submitPass->getAttribs()
						);
						?>
					</td>
				</tr>
		</table>
	</form>
</div>
<script type="text/javascript">
$(document).ready(function() {
	$("#<?php echo $this->element->getId();?>").validationEngine();
});
</script>