<form method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getAttrib('id');?>" class="<?php echo $this->element->getAttrib('class');?>" enctype="<?php echo $this->element->getEncType();?>">
	<table  border="0" cellpadding="0" cellspacing="0" class="popup-table">
		<col width="50" />
		<col />
		<tr>
			<td class="label" valign="top">
				<?php
				$attribs = array();
				if ($this->element->id->isRequired()) {
					$attribs['class'] = 'required';
				}
				echo $this->formLabel($this->element->name->getName(), $this->element->id->getLabel(), $attribs);?>
			</td>
			<td class="input">
				<?php
					echo $this->{$this->element->id->helper}(
						$this->element->id->getName(),
						$this->element->id->getValue(),
						$this->element->id->getAttribs()
					);
				?>
				<?php if('<ul class="errors"><li></li></ul>'!=($this->element->id->getMessages())){ echo  $this->formErrors($this->element->id->getMessages());} ?>
				<div class="hint"><?php echo $this->element->id->getDescription(); ?></div>
			</td>
		</tr>
		<tr>
			<td class="label" valign="top">
				<?php
				$attribs = array();
				if ($this->element->name->isRequired()) {
					$attribs['class'] = 'required';
				}
				echo $this->formLabel($this->element->name->getName(), $this->element->name->getLabel(), $attribs);?>
			</td>
			<td class="input">
				<?php
					echo $this->{$this->element->name->helper}(
						$this->element->name->getName(),
						$this->element->name->getValue(),
						$this->element->name->getAttribs()
					);
				?>
				<?php if('<ul class="errors"><li></li></ul>'!=($this->element->name->getMessages())){ echo  $this->formErrors($this->element->name->getMessages());} ?>
				<div class="hint"><?php echo $this->element->name->getDescription(); ?></div>
			</td>
		</tr>
		<tr>
			<td class="label" valign="top">
				<?php
				$attribs = array();
				if ($this->element->email->isRequired()) {
					$attribs['class'] = 'required';
				}
				echo $this->formLabel($this->element->email->getName(), $this->element->email->getLabel(), $attribs);?>
			</td>
			<td class="input">
				<?php
				echo $this->{$this->element->email->helper}(
							$this->element->email->getName(),
							$this->element->email->getValue(),
							$this->element->email->getAttribs()
						);
				?>
				<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->email->getMessages()))){ echo $this->formErrors($this->element->email->getMessages());} ?>
				<p class="description"><?php echo $this->element->email->getDescription() ?></p>
			</td>
		</tr>
		<tr>
			<td class="label" valign="top">
				<?php
				$attribs = array();
				if ($this->element->phone->isRequired()) {
					$attribs['class'] = 'required';
				}
				echo $this->formLabel($this->element->phone->getName(), $this->element->phone->getLabel(), $attribs);?>
			</td>
			<td class="input">
				<?php
					echo $this->{$this->element->phone->helper}(
								$this->element->phone->getName(),
								$this->element->phone->getValue(),
								$this->element->phone->getAttribs()
							);
				?>
				<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->phone->getMessages()))){ echo $this->formErrors($this->element->phone->getMessages());} ?>
				<p class="description"><?php echo $this->element->phone->getDescription() ?></p>
			</td>
		</tr>
		<tr>
			<td class="label" valign="top">
				<?php
				$attribs = array();
				if ($this->element->comments->isRequired()) {
					$attribs['class'] = 'required';
				}
				echo $this->formLabel($this->element->comments->getName(), $this->element->comments->getLabel(), $attribs);?>
			</td>
			<td class="input">
				<?php
					echo $this->{$this->element->comments->helper}(
								$this->element->comments->getName(),
								$this->element->comments->getValue(),
								$this->element->comments->getAttribs()
							);
				?>
				<?php if('<ul class="errors"><li></li></ul>'!=($this->element->comments->getMessages())){ echo  $this->formErrors($this->element->comments->getMessages());} ?>
				<div class="hint"><?php echo $this->element->comments->getDescription(); ?></div>
			</td>
		</tr>
		<tr>
			<td class="label">&nbsp;</td>
			<td class="input">
				<?php echo $this->{$this->element->submit->helper}(
								$this->element->submit->getName(),
								$this->element->submit->getValue(),
								$this->element->submit->getAttribs()
							);
				?>
			</td>
		</tr>
		<tr>
			<td colspan="2">&nbsp;</td>
		</tr>
	</table>
</form>
<script type="text/javascript">
$(document).ready(function() {
	$("#<?php echo $this->element->getAttrib('id');?>").validationEngine({
		promptPosition : "topRight"
	});
});
</script>