<form method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getId();?>" enctype="<?php echo $this->element->getEncType();?>">
	<div class="box">
		<table cellpadding="0" cellspacing="0" class="box-tbl-info">
		<col width="250" />
			<tr>
			<th valign="top">
				<?php
				$attribs = array();
				if ($this->element->openid_identifier->isRequired()) {
					$attribs['class'] = 'required';
				}
				echo $this->formLabel($this->element->openid_identifier->getName(), $this->element->openid_identifier->getLabel(), $attribs);?>
			</th>
			<td>
				<?php
				echo $this->{$this->element->openid_identifier->helper}(
							$this->element->openid_identifier->getName(),
							$this->element->openid_identifier->getValue(),
							$this->element->openid_identifier->getAttribs()
						);
				?>
				<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->openid_identifier->getMessages()))){ echo $this->formErrors($this->element->openid_identifier->getMessages());} ?>
				<p class="red-warning"><small><?php echo $this->element->openid_identifier->getDescription() ?></small></p>
			</td>
			<td align="left">
				<?php echo $this->{$this->element->submit->helper}(
								$this->element->submit->getName(),
								$this->element->submit->getValue(),
								$this->element->submit->getAttribs()
							);
				?>
			</td>
		</tr>
		</table>
	</div>
</form>
<?php $this->headScript()->captureStart() ?>
	$(document).ready(function() {
		$("#<?php echo $this->element->getId();?>").validationEngine();
	});
<?php $this->headScript()->captureEnd() ?>