<form method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getAttrib('id');?>" class="<?php echo $this->element->getAttrib('class');?>" enctype="<?php echo $this->element->getEncType();?>">
	<table  border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td align="right">
				<?php
				$attribs = array();
				if ($this->element->term->isRequired()) {
					$attribs['class'] = 'required';
				}
				?>
				<?php
					echo $this->{$this->element->term->helper}(
								$this->element->term->getName(),
								$this->element->term->getValue(),
								$this->element->term->getAttribs()
							);
				?>
			</td>
			<td align="left">
				<?php if('<ul class="errors"><li></li></ul>'!=($this->element->term->getMessages())){ echo  $this->formErrors($this->element->term->getMessages());} ?>
				<div class="hint"><?php echo $this->element->term->getDescription(); ?></div>
				<?php echo $this->{$this->element->submit->helper}(
								$this->element->submit->getName(),
								$this->element->submit->getValue(),
								$this->element->submit->getAttribs()
							);
				?>
			</td>
		</tr>
	</table>
</form>
<?php $this->headScript()->captureStart() ?>
	$(document).ready(function() {
		$("#<?php echo $this->element->getId();?>").validationEngine();
	});
<?php $this->headScript()->captureEnd() ?>