<div class="previzualizare1">
    <table width="100%" border="0" cellpadding="0" cellspacing="0" class="cart-delivery-tbl">
        <col width="200"/>
        <tr>
            <td colspan="2" align="center">
                <small class="fR">Campurile marcate cu <img src="/images/required.gif" border="0" align="absmiddle"
                                                            alt=""/> sunt obligatorii.
                </small>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <?php
                    $attribs = array();
                    if ($this->element->createaccount->isRequired()) {
                        $attribs['class'] = 'required';
                    }
                    echo $this->formLabel($this->element->createaccount->getName(), $this->element->createaccount->getLabel(), $attribs);
                    ?>
                </p>
            </td>
            <td>
                <?php
                echo $this->{$this->element->createaccount->helper}(
                    $this->element->createaccount->getName(),
                    $this->element->createaccount->getCheckedValue(),
                    $this->element->createaccount->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->element->createaccount->getMessages())) {
                    echo $this->formErrors($this->element->createaccount->getMessages());
                } ?>
                <div class="hint"><?php echo $this->element->createaccount->getDescription(); ?></div>
            </td>
        </tr>
    </table>
    <div class="clear">&nbsp;</div>
    <div id="loginDAtaD">
        <table width="100%" border="0" cellpadding="0" cellspacing="0" class="cart-delivery-tbl" id="loginDataA">
            <col width="200"/>
            <tr>
                <td colspan="2">
                    <h2>Date cont</h2>
                </td>
            </tr>
            <tr>
                <td>
                    <p>
                        <?php
                        $attribs = array();
                        $attribs['class'] = 'required';
                        echo $this->formLabel($this->element->username->getName(), $this->element->username->getLabel(), $attribs);
                        ?>
                    </p>
                </td>
                <td>
                    <?php
                    echo $this->{$this->element->username->helper}
                    (
                        $this->element->username->getName(),
                        $this->element->username->getValue(),
                        $this->element->username->getAttribs()
                    );
                    ?>
                    <?php if ('<ul class="errors"><li></li></ul>' != ($this->formErrors($this->element->username->getMessages()))) {
                        echo $this->formErrors($this->element->username->getMessages());
                    } ?>
                    <p class="description">
                        <small><?php echo $this->element->username->getDescription() ?></small>
                    </p>
                </td>
            </tr>
            <tr>
                <td>
                    <p>
                        <?php
                        $attribs = array();
                        //				if ($this->element->password->isRequired()) {
                        $attribs['class'] = 'required';
                        //				}
                        echo $this->formLabel($this->element->password->getName(), $this->element->password->getLabel(), $attribs);
                        ?>
                    </p>
                </td>
                <td>
                    <?php
                    echo $this->{$this->element->password->helper}(
                        $this->element->password->getName(),
                        $this->element->password->getValue(),
                        $this->element->password->getAttribs()
                    );
                    ?>
                    <?php if ('<ul class="errors"><li></li></ul>' != ($this->formErrors($this->element->password->getMessages()))) {
                        echo $this->formErrors($this->element->password->getMessages());
                    } ?>
                    <p class="description">
                        <small><?php echo $this->element->password->getDescription() ?></small>
                    </p>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    &nbsp;
                </td>
            </tr>
        </table>
    </div>

    <table width="100%" border="0" cellpadding="0" cellspacing="0" class="cart-delivery-tbl">
        <col width="200"/>
        <tr>
            <td colspan="2">
                <h2>Adresa de Facturare</h2>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <?php
                    $attribs = array();
                    if ($this->element->email->isRequired()) {
                        $attribs['class'] = 'required';
                    }
                    echo $this->formLabel($this->element->email->getName(), $this->element->email->getLabel(), $attribs);
                    ?>
                </p>
            </td>
            <td>
                <?php
                echo $this->{$this->element->email->helper}
                (
                    $this->element->email->getName(),
                    $this->element->email->getValue(),
                    $this->element->email->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->formErrors($this->element->email->getMessages()))) {
                    echo $this->formErrors($this->element->email->getMessages());
                } ?>
                <p class="red-warning">
                    <small><?php echo $this->element->email->getDescription() ?></small>
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <?php
                    $attribs = array();
                    if ($this->element->firstname->isRequired()) {
                        $attribs['class'] = 'required';
                    }
                    echo $this->formLabel($this->element->firstname->getName(), $this->element->firstname->getLabel(), $attribs);
                    ?>
                </p>
            </td>
            <td>
                <?php
                echo $this->{$this->element->firstname->helper}
                (
                    $this->element->firstname->getName(),
                    $this->element->firstname->getValue(),
                    $this->element->firstname->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->formErrors($this->element->firstname->getMessages()))) {
                    echo $this->formErrors($this->element->firstname->getMessages());
                } ?>
                <p class="red-warning">
                    <small><?php echo $this->element->firstname->getDescription() ?></small>
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <?php
                    $attribs = array();
                    if ($this->element->lastname->isRequired()) {
                        $attribs['class'] = 'required';
                    }
                    echo $this->formLabel($this->element->lastname->getName(), $this->element->lastname->getLabel(), $attribs);
                    ?>
                </p>
            </td>
            <td>
                <?php
                echo $this->{$this->element->lastname->helper}
                (
                    $this->element->lastname->getName(),
                    $this->element->lastname->getValue(),
                    $this->element->lastname->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->formErrors($this->element->lastname->getMessages()))) {
                    echo $this->formErrors($this->element->lastname->getMessages());
                } ?>
                <p class="red-warning">
                    <small><?php echo $this->element->lastname->getDescription() ?></small>
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <?php
                    $attribs = array();
                    if ($this->element->address->isRequired()) {
                        $attribs['class'] = 'required';
                    }
                    echo $this->formLabel($this->element->address->getName(), $this->element->address->getLabel(), $attribs);
                    ?>
                </p>
            </td>
            <td>
                <?php
                echo $this->{$this->element->address->helper}(
                    $this->element->address->getName(),
                    $this->element->address->getValue(),
                    $this->element->address->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->formErrors($this->element->address->getMessages()))) {
                    echo $this->formErrors($this->element->address->getMessages());
                } ?>
                <p class="red-warning">
                    <small><?php echo $this->element->address->getDescription() ?></small>
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <?php
                    $attribs = array();
                    if ($this->element->county->isRequired()) {
                        $attribs['class'] = 'required';
                    }
                    echo $this->formLabel($this->element->county->getName(), $this->element->county->getLabel(), $attribs);
                    ?>
                </p>
            </td>
            <td>
                <div id="suggestCounty">
                    <?php
                    echo $this->{$this->element->county->helper}(
                        $this->element->county->getName(),
                        $this->element->county->getValue(),
                        $this->element->county->getAttribs()
                    );
                    ?>
                    <?php if ('<ul class="errors"><li></li></ul>' != ($this->element->county->getMessages())) {
                        echo $this->formErrors($this->element->county->getMessages());
                    } ?>
                    <div class="hint"><?php echo $this->element->county->getDescription(); ?></div>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <?php
                    $attribs = array();
                    if ($this->element->city->isRequired()) {
                        $attribs['class'] = 'required';
                    }
                    echo $this->formLabel($this->element->city->getName(), $this->element->city->getLabel(), $attribs);
                    ?>
                </p>
            </td>
            <td>
                <div id="suggestCity">
                    <?php
                    echo $this->{$this->element->city->helper}(
                        $this->element->city->getName(),
                        $this->element->city->getValue(),
                        $this->element->city->getAttribs()
                    );
                    ?>
                    <?php if ('<ul class="errors"><li></li></ul>' != ($this->element->city->getMessages())) {
                        echo $this->formErrors($this->element->city->getMessages());
                    } ?>
                    <div class="hint"><?php echo $this->element->city->getDescription(); ?></div>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <?php
                    $attribs = array();
                    if ($this->element->zip->isRequired()) {
                        $attribs['class'] = 'required';
                    }
                    echo $this->formLabel($this->element->zip->getName(), $this->element->zip->getLabel(), $attribs);
                    ?>
                </p>
            </td>
            <td>
                <?php
                echo $this->{$this->element->zip->helper}(
                    $this->element->zip->getName(),
                    $this->element->zip->getValue(),
                    $this->element->zip->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->formErrors($this->element->zip->getMessages()))) {
                    echo $this->formErrors($this->element->zip->getMessages());
                } ?>
                <p class="red-warning">
                    <small><?php echo $this->element->zip->getDescription() ?></small>
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <?php
                    $attribs = array();
                    if ($this->element->phone->isRequired()) {
                        $attribs['class'] = 'required';
                    }
                    echo $this->formLabel($this->element->phone->getName(), $this->element->phone->getLabel(), $attribs);
                    ?>
                </p>
            </td>
            <td>
                <?php
                echo $this->{$this->element->phone->helper}(
                    $this->element->phone->getName(),
                    $this->element->phone->getValue(),
                    $this->element->phone->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->formErrors($this->element->phone->getMessages()))) {
                    echo $this->formErrors($this->element->phone->getMessages());
                } ?>
                <p class="red-warning">
                    <small><?php echo $this->element->phone->getDescription() ?></small>
                </p>
            </td>
        </tr>
    </table>
    <div class="clear">&nbsp;</div>
    <table width="95%" cellpadding="0" cellspacing="0" class="cart-delivery-tbl">
        <col width="200"/>
        <tr>
            <td colspan="2">
                <h2>Adresa de livrare</h2>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <?php
                    $attribs = array();
                    if ($this->element->firstnameS->isRequired()) {
                        $attribs['class'] = 'required';
                    }
                    echo $this->formLabel($this->element->firstnameS->getName(), $this->element->firstnameS->getLabel(), $attribs);
                    ?>
                </p>
            </td>
            <td>
                <?php
                echo $this->{$this->element->firstnameS->helper}(
                    $this->element->firstnameS->getName(),
                    $this->element->firstnameS->getValue(),
                    $this->element->firstnameS->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->element->firstnameS->getMessages())) {
                    echo $this->formErrors($this->element->firstnameS->getMessages());
                } ?>
                <p class="description"><?php echo $this->element->firstnameS->getDescription(); ?></p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <?php
                    $attribs = array();
                    if ($this->element->lastnameS->isRequired()) {
                        $attribs['class'] = 'required';
                    }
                    echo $this->formLabel($this->element->lastnameS->getName(), $this->element->lastnameS->getLabel(), $attribs);
                    ?>
                </p>
            </td>
            <td>
                <?php
                echo $this->{$this->element->lastnameS->helper}(
                    $this->element->lastnameS->getName(),
                    $this->element->lastnameS->getValue(),
                    $this->element->lastnameS->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->element->lastnameS->getMessages())) {
                    echo $this->formErrors($this->element->lastnameS->getMessages());
                } ?>
                <p class="description"><?php echo $this->element->lastnameS->getDescription(); ?></p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <?php
                    $attribs = array();
                    if ($this->element->addressS->isRequired()) {
                        $attribs['class'] = 'required';
                    }
                    echo $this->formLabel($this->element->addressS->getName(), $this->element->addressS->getLabel(), $attribs);
                    ?>
                </p>
            </td>
            <td>
                <?php
                echo $this->{$this->element->addressS->helper}(
                    $this->element->addressS->getName(),
                    $this->element->addressS->getValue(),
                    $this->element->addressS->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->element->addressS->getMessages())) {
                    echo $this->formErrors($this->element->addressS->getMessages());
                } ?>
                <p class="description"><?php echo $this->element->addressS->getDescription(); ?></p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <?php
                    $attribs = array();
                    if ($this->element->stateS->isRequired()) {
                        $attribs['class'] = 'required';
                    }
                    echo $this->formLabel($this->element->stateS->getName(), $this->element->stateS->getLabel(), $attribs);
                    ?>
                </p>
            </td>
            <td>
                <?php
                echo $this->{$this->element->stateS->helper}(
                    $this->element->stateS->getName(),
                    $this->element->stateS->getValue(),
                    $this->element->stateS->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->element->stateS->getMessages())) {
                    echo $this->formErrors($this->element->stateS->getMessages());
                } ?>
                <p class="description"><?php echo $this->element->stateS->getDescription(); ?></p>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    <?php
                    $attribs = array();
                    if ($this->element->zipcodeS->isRequired()) {
                        $attribs['class'] = 'required';
                    }
                    echo $this->formLabel($this->element->zipcodeS->getName(), $this->element->zipcodeS->getLabel(), $attribs);
                    ?>
                </p>
            </td>
            <td>
                <?php
                echo $this->{$this->element->zipcodeS->helper}(
                    $this->element->zipcodeS->getName(),
                    $this->element->zipcodeS->getValue(),
                    $this->element->zipcodeS->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->element->zipcodeS->getMessages())) {
                    echo $this->formErrors($this->element->zipcodeS->getMessages());
                } ?>
                <p class="description"><?php echo $this->element->zipcodeS->getDescription(); ?></p>
            </td>
        </tr>
    </table>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        var hiddenperson;
//    hiddenperson = $("#loginDataA").detach();
        $("input[name=createaccount]").click(function () {
            if ($(this).is(':checked')) {
                if (hiddenperson != null) {
                    hiddenperson.appendTo('#loginDAtaD');
                    hiddenperson = null;
                }
            } else {
                if (hiddenperson == null) {
                    hiddenperson = $("#loginDataA").detach();
                }
            }

        });
    });
</script>