<div class="box">
    <form method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction(); ?>"
          id="<?php echo $this->element->getAttrib('id'); ?>" class="<?php echo $this->element->getAttrib('class'); ?>"
          enctype="<?php echo $this->element->getEncType(); ?>">
        <table width="100%" cellpadding="0" cellspacing="0" border="0" class="box-tbl-info">
            <col width="200"/>
            <tr>
                <th valign="top">
                    <?php
                    $attribs = array();
                    if ($this->element->name->isRequired()) {
                        $attribs['class'] = 'required';
                    }
                    echo $this->formLabel($this->element->name->getName(), $this->element->name->getLabel(), $attribs); ?>
                </th>
                <td>
                    <?php
                    echo $this->{$this->element->name->helper}(
                        $this->element->name->getName(),
                        $this->element->name->getValue(),
                        $this->element->name->getAttribs()
                    );
                    ?>
                    <?php if ('<ul class="errors"><li></li></ul>' != ($this->element->name->getMessages())) {
                        echo $this->formErrors($this->element->name->getMessages());
                    } ?>
                    <div class="hint"><?php echo $this->element->name->getDescription(); ?></div>
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <?php echo $this->{$this->element->submit->helper}(
                        $this->element->submit->getName(),
                        $this->element->submit->getValue(),
                        $this->element->submit->getAttribs()
                    );
                    ?>
                </td>
            </tr>
        </table>
    </form>
</div>
<?php $this->headScript()->captureStart() ?>
$(document).ready(function() {

});
<?php $this->headScript()->captureEnd() ?>

