<form method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction(); ?>"
      id="<?php echo $this->element->getAttrib('id'); ?>" class="<?php echo $this->element->getAttrib('class'); ?>"
      enctype="<?php echo $this->element->getEncType(); ?>">
    <table>
        <tr>
            <td>
                <?php
                $attribs = array();
                echo $this->formLabel($this->element->unsubscribe->getName(), $this->element->unsubscribe->getLabel(), $attribs); ?>
            </td>
            <td>
                <?php
                echo $this->{$this->element->unsubscribe->helper}(
                    $this->element->unsubscribe->getName(),
                    $this->element->unsubscribe->getValue(),
                    $this->element->unsubscribe->getAttribs()
                );
                ?>
            </td>
            <td>
                <?php
                echo $this->{$this->element->submit->helper}(
                    $this->element->submit->getName(),
                    $this->element->submit->getValue(),
                    $this->element->submit->getAttribs()
                );
                ?>
            </td>
        </tr>
    </table>
</form>
<?php $this->headScript()->captureStart() ?>
$(document).ready(function() {
$("#<?php echo $this->element->getId(); ?>").validationEngine();
});
<?php $this->headScript()->captureEnd() ?>