<link rel="stylesheet" type="text/css" href="/js/jquery-tools/tablesorter/blue/style.css" />
<script type="text/javascript" src="/js/jquery-tools/tablesorter/jquery.tablesorter.js"></script>
<script type="text/javascript" src="/js/jquery-tools/tablesorter/addons/jquery.tablesorter.pager.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $("#sortProd").tablesorter({
		widthFixed: false,
		widgets: ['zebra'],
		headers: {
			4: {sorter: false}
		}
	});
});
</script>
<?php if(!empty($this->message)) : ?>
	<?php foreach($this->message as $value) : ?>
		<div class="empty10"></div>
		<?php echo $value; ?>
	<?php endforeach; ?>
<?php endif; ?>

<div class="empty10"></div>
<div class="fL">
	<a class="button1" href="/admin/cms/media-add"><small>Adauga Fisier</small></a>
	<a class="button1" href="/admin/cms/media-search"><small>Cautare Fisier</small></a>
</div>
<div class="fR"><?php echo $this->form; ?></div>
<div class="empty10"></div>
<div class="clear"></div>

<?php if($this->result) : ?>
	<table id="sortProd" cellspacing="1" class="tablesorter">
		<col width="80" />
		<col width="80" />
		<col width="" />
		<col width="" />
		<col width="120" />
		<thead>
			<tr>
				<th>Adaugat</th>
				<th>Tipul</th>
				<th><?php echo Zend_Registry::get('translate')->_('cms_pages_table_url'); ?></th>
				<th>Note</th>
				<th><?php echo Zend_Registry::get('translate')->_('cms_pages_table_actions'); ?></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($this->result as $value) : ?>
			<tr>
				<td align="center"><?php echo $value->getCreated()?date('Y-m-d', $value->getCreated()):'-'; ?></td>
				<td align="left"><?php echo $value->getType(); ?></td>
				<td align="left"><a target="_blank" href="<?php echo $value->getUrl(); ?>"><?php echo $value->getUrl(); ?></a></td>
				<td align="left"><?php echo $value->getNote(); ?></td>
				<td align="center">
					<a href="/admin/cms/media-edit/id/<?php echo $value->getId(); ?><?php echo $this->curPage?'/page/'.$this->curPage:''; ?>">Modifica</a>
					 | 
					<a href="/admin/cms/media-delete/id/<?php echo $value->getId(); ?><?php echo $this->curPage?'/page/'.$this->curPage:''; ?>" class="confirmDelete"><?php echo Zend_Registry::get('translate')->_('cms_pages_table_delete'); ?></a>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>

	<!-- BEGIN: Paginare -->
	<?php $itemCountPerPage = $this->itemCountPerPage; ?>
	<?php $totalItemCount = $this->totalItemCount; ?>
	<div class="wrap-paginare">
		<?php if($itemCountPerPage < $totalItemCount) { ?>
		<ul class="paginare fL">
			<li><?php echo Zend_Registry::get('translate')->_('paginare'); ?> </li>
			<?php echo $this->result; ?>
		</ul>
		<?php } ?>
		<div class="productsPerPage fR">
			<label for="productsPerPage"><?php echo Zend_Registry::get('translate')->_('products_display_on_page'); ?></label>
			<select name="productsPerPage" id="productsPerPage" <?php if(!empty($_SESSION['adminProdsPage'])) { echo 'class="selected"'; } ?>>
				<?php foreach($this->adminProdsPageValues as $value) : ?>
				<option value="<?php echo $value->getValue(); ?>" <?php if(!empty($_SESSION['adminProdsPage']) && $_SESSION['adminProdsPage'] == $value->getValue()) { echo 'selected="selected"'; } ?>><?php echo $value->getValue(); ?></option>
				<?php endforeach; ?>
			</select>
		</div>
	</div>
	<!-- END: Paginare -->

	<div id="confirmStatusChange" title="<?php echo Zend_Registry::get('translate')->_('confirmation_message'); ?>" style="display:none;"><?php echo Zend_Registry::get('translate')->_('cms_pages_message_status_change'); ?></div>
	<div id="confirmDelete" title="<?php echo Zend_Registry::get('translate')->_('confirmation_message'); ?>" style="display:none;"><?php echo Zend_Registry::get('translate')->_('cms_pages_message_delete'); ?></div>
<?php else : ?>
	<div>Nu exista fisiere</div>
<?php endif; ?>

<?php $this->headScript()->captureStart(); ?>
	$(document).ready(function() {
		$('.confirmStatusChange').click(function() {
			var link = $(this);
			$("#confirmStatusChange").dialog({
				bgiframe: true,
				height: 150,
				width: 400,
				modal: true,
				buttons: {
					'<?php echo Zend_Registry::get('translate')->_('confirmation_yes'); ?>': function() {
						$(this).dialog('close').dialog('destroy');
						window.location.href = link.attr('href');
					},
					'<?php echo Zend_Registry::get('translate')->_('confirmation_no'); ?>': function() {
						$(this).dialog('close').dialog('destroy');
					}
				}
			});
			return false;
		});

		$('.confirmDelete').click(function() {
			var link = $(this);
			$("#confirmDelete").dialog({
				bgiframe: true,
				height: 150,
				width: 400,
				modal: true,
				buttons: {
					'<?php echo Zend_Registry::get('translate')->_('confirmation_yes'); ?>': function() {
						$(this).dialog('close').dialog('destroy');
						window.location.href = link.attr('href');
					},
					'<?php echo Zend_Registry::get('translate')->_('confirmation_no'); ?>': function() {
						$(this).dialog('close').dialog('destroy');
					}
				}
			});
			return false;
		});
	});
<?php $this->headScript()->captureEnd(); ?>

<script type="text/javascript">
	$('#productsPerPage').change(function() {
		var value = $('#productsPerPage').val();
		window.location = '/admin/settings/productsperpage/page/media/value/'+value;
	});
</script>