<?php if (!empty($this->message)) : ?>
    <?php foreach ($this->message as $value) : ?>
        <?php echo $value; ?>
    <?php endforeach; ?>
<?php endif; ?>

<div class="empty10"></div>
<?php if ($this->result) : ?>
    <table class="tableListingsAll" width="100%" cellpadding="0" cellspacing="0" border="0">
        <col width="120"/>
        <col width=""/>
        <col width="170"/>
        <col width="180"/>
        <thead>
        <tr>
            <th><?php echo Zend_Registry::get('translate')->_('marketing_subscribers_table_subscribed'); ?></th>
            <th><?php echo Zend_Registry::get('translate')->_('marketing_subscribers_table_email'); ?></th>
            <th><?php echo Zend_Registry::get('translate')->_('marketing_subscribers_table_unsubscribe_code'); ?></th>
            <th>
                Status
            </th>
            <th><?php echo Zend_Registry::get('translate')->_('marketing_subscribers_table_actions'); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->result as $value) : ?>
            <tr>
                <td align="center"><?php echo($value->getCreated() ? date('Y-m-d', $value->getCreated()) : '-'); ?></td>
                <td align="left"><?php echo strip_tags($value->getEmail()); ?></td>
                <td align="center"><?php echo strip_tags($value->getUnsubscribe()); ?></td>
                <td align="center">
                    <a href="/admin/newsletter/subscribersstatuschange/id/<?php echo $value->getId(); ?><?php echo $this->curPage ? '/page/' . $this->curPage : ''; ?>"><?php echo($value->getStatus() ? Zend_Registry::get('translate')->_('marketing_subscribers_table_active') : Zend_Registry::get('translate')->_('marketing_subscribers_table_inactive')); ?></a>
                </td>
                <td align="center">
                    <a href="/admin/newsletter/deleteemail/id/<?php echo $value->getId(); ?><?php echo $this->curPage ? '/page/' . $this->curPage : ''; ?>"
                       class="confirmDelete">
                        <img src="/images/admin/icons/delete.png" alt="sterge"/>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <!-- BEGIN: Paginare -->
    <?php $itemCountPerPage = $this->itemCountPerPage; ?>
    <?php $totalItemCount = $this->totalItemCount; ?>
    <?php if ($itemCountPerPage < $totalItemCount) { ?>
        <?php echo $this->result; ?>
    <?php } ?>

    <!-- END: Paginare -->

    <div id="confirmStatusChange" title="<?php echo Zend_Registry::get('translate')->_('confirmation_message'); ?>"
         style="display:none;"><?php echo Zend_Registry::get('translate')->_('marketing_subscribers_message_status_change'); ?></div>
    <div id="confirmDelete" title="<?php echo Zend_Registry::get('translate')->_('confirmation_message'); ?>"
         style="display:none;"><?php echo Zend_Registry::get('translate')->_('marketing_subscribers_message_delete'); ?></div>
<?php else : ?>
    <div><?php echo Zend_Registry::get('translate')->_('marketing_subscribers_else'); ?></div>
<?php endif; ?>

<?php $this->headScript()->captureStart(); ?>
$(document).ready(function() {
$('.confirmStatusChange').click(function() {
var link = $(this);
$("#confirmStatusChange").dialog({
bgiframe: true,
height: 150,
width: 400,
modal: true,
buttons: {
'<?php echo Zend_Registry::get('translate')->_('confirmation_yes'); ?>': function() {
$(this).dialog('close').dialog('destroy');
window.location.href = link.attr('href');
},
'<?php echo Zend_Registry::get('translate')->_('confirmation_no'); ?>': function() {
$(this).dialog('close').dialog('destroy');
}
}
});
return false;
});

$('.confirmDelete').click(function() {
var link = $(this);
$("#confirmDelete").dialog({
bgiframe: true,
height: 150,
width: 400,
modal: true,
buttons: {
'<?php echo Zend_Registry::get('translate')->_('confirmation_yes'); ?>': function() {
$(this).dialog('close').dialog('destroy');
window.location.href = link.attr('href');
},
'<?php echo Zend_Registry::get('translate')->_('confirmation_no'); ?>': function() {
$(this).dialog('close').dialog('destroy');
}
}
});
return false;
});
});
<?php $this->headScript()->captureEnd(); ?>
