<form method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction(); ?>"
      id="<?php echo $this->element->getAttrib('id'); ?>" class="<?php echo $this->element->getAttrib('class'); ?>"
      enctype="<?php echo $this->element->getEncType(); ?>">
    <table width="100%" cellpadding="0" cellspacing="0" border="0" class="tableAdmin box-tbl-info">
        <col width="200"/>
        <col width=""/>
        <tr>
            <th valign="middle">
                <?php
                $attribs = array();
                if ($this->element->order->isRequired()) {
                    $attribs['class'] = 'required';
                }
                echo $this->formLabel($this->element->order->getName(), $this->element->order->getLabel(), $attribs); ?>
            </th>
            <td>
                <?php
                echo $this->{$this->element->order->helper}(
                    $this->element->order->getName(),
                    $this->element->order->getValue(),
                    $this->element->order->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->element->order->getMessages())) {
                    echo $this->formErrors($this->element->order->getMessages());
                } ?>
                <div class="hint"><?php echo $this->element->order->getDescription(); ?></div>
            </td>
        </tr>
        <tr>
            <th valign="middle">
                <?php
                $attribs = array();
                if ($this->element->name->isRequired()) {
                    $attribs['class'] = 'required';
                }
                echo $this->formLabel($this->element->name->getName(), $this->element->name->getLabel(), $attribs); ?>
            </th>
            <td>
                <?php
                echo $this->{$this->element->name->helper}(
                    $this->element->name->getName(),
                    $this->element->name->getValue(),
                    $this->element->name->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->element->name->getMessages())) {
                    echo $this->formErrors($this->element->name->getMessages());
                } ?>
                <div class="hint"><?php echo $this->element->name->getDescription(); ?></div>
            </td>
        </tr>
        <tr>
            <th>&nbsp;</th>
            <td>
                <?php echo $this->{$this->element->submit->helper}(
                    $this->element->submit->getName(),
                    $this->element->submit->getValue(),
                    $this->element->submit->getAttribs()
                );
                ?>
            </td>
        </tr>
    </table>
</form>

<script type="text/javascript">
    $(document).ready(function () {
        $("#<?php echo $this->element->getAttrib('id'); ?>").validationEngine();
    });
</script>