<form method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getAttrib('id');?>" class="<?php echo $this->element->getAttrib('class');?>" enctype="<?php echo $this->element->getEncType();?>">
	<table cellpadding="0" cellspacing="0" border="0" class="tableAdmin box-tbl-info">
		<col width="200" />
		<col width="" />
		<tr>
			<th valign="middle">
				<?php
				$attribs = array();
				if ($this->element->image->isRequired()) {
					$attribs['class'] = 'required';
				}
				echo $this->formLabel($this->element->image->getName(), $this->element->image->getLabel(), $attribs);?>
			</th>
			<td>
				<?php
					echo $this->{$this->element->image->helper}(
								$this->element->image->getName(),
								$this->element->image->getValue(),
								$this->element->image->getAttribs()
							);
				?>
				<?php if('<ul class="errors"><li></li></ul>'!=($this->element->image->getMessages())){ echo  $this->formErrors($this->element->image->getMessages());} ?>
				<div class="hint"><?php echo $this->element->image->getDescription(); ?></div>
			</td>
		</tr>
		<tr>
			<th>&nbsp;</th>
			<td>
				<?php echo $this->{$this->element->submit->helper}(
						$this->element->submit->getName(),
						$this->element->submit->getValue(),
						$this->element->submit->getAttribs()
					);
				?>
			</td>
		</tr>
	</table>
</form>

<script type="text/javascript">
$(document).ready(function(){
	$("#<?php echo $this->element->getAttrib('id'); ?>").validationEngine();
});
</script>