<div>
	<form method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getAttrib('id');?>" class="<?php echo $this->element->getAttrib('class');?>"  enctype="<?php echo $this->element->getEncType();?>">
		<div class="fL">
			<?php
				echo $this->{$this->element->txtHeaderSearch->helper}
						(
							$this->element->txtHeaderSearch->getName(),
							$this->element->txtHeaderSearch->getValue(),
							$this->element->txtHeaderSearch->getAttribs()
						);
			?>
			<?php if('<ul class="errors"><li></li></ul>' != ($this->element->txtHeaderSearch->getMessages())) { echo $this->formErrors($this->element->txtHeaderSearch->getMessages()); } ?>
			<div class="hint"><?php echo $this->element->txtHeaderSearch->getDescription(); ?></div>
		</div>
		<div class="fR">
			&nbsp;
			<?php
				echo $this->{$this->element->submit->helper}
						(
							$this->element->submit->getName(),
							$this->element->submit->getValue(),
							$this->element->submit->getAttribs()
						);
			?>

		</div>
		<div class="clear"></div>
	</form>
</div>

<?php $this->headScript()->captureStart() ?>
	$(document).ready(function() {
		$("#<?php echo $this->element->getAttrib('id');?>").validationEngine();
	});
<?php $this->headScript()->captureEnd() ?>