<form method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction(); ?>"
      id="<?php echo $this->element->getAttrib('id'); ?>" class="<?php echo $this->element->getAttrib('class'); ?>"
      enctype="<?php echo $this->element->getEncType(); ?>">
    <table width="100%" cellpadding="0" cellspacing="0" border="0" class="tableAdmin box-tbl-info">
        <col width="200"/>
        <col width=""/>
        <tr>
            <th valign="middle">
                <?php
                $attribs = array();
                if ($this->element->name->isRequired()) {
                    $attribs['class'] = 'required';
                }
                echo $this->formLabel($this->element->name->getName(), $this->element->name->getLabel(), $attribs); ?>
            </th>
            <td>
                <?php
                echo $this->{$this->element->name->helper}(
                    $this->element->name->getName(),
                    $this->element->name->getValue(),
                    $this->element->name->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->element->name->getMessages())) {
                    echo $this->formErrors($this->element->name->getMessages());
                } ?>
                <div class="hint"><?php echo $this->element->name->getDescription(); ?></div>
            </td>
        </tr>
        <tr>
            <th valign="middle">
                <?php
                $attribs = array();
                if ($this->element->image->isRequired()) {
                    $attribs['class'] = 'required';
                }
                echo $this->formLabel($this->element->image->getName(), $this->element->image->getLabel(), $attribs); ?>
            </th>
            <td>
                <?php
                echo $this->{$this->element->image->helper}(
                    $this->element->image->getName(),
                    $this->element->image->getValue(),
                    $this->element->image->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->element->image->getMessages())) {
                    echo $this->formErrors($this->element->image->getMessages());
                } ?>
                <div class="hint"><?php echo $this->element->image->getDescription(); ?></div>
                <?php if ($this->element->imageOld->getValue()) { ?>
                    <br/>
                    <img src="/media/productsInstructions/<?php echo $this->element->imageOld->getValue(); ?>" alt=""/>
                <?php } ?>
            </td>
        </tr>
        <tr>
            <th valign="middle">
                <?php
                $attribs = array();
                if ($this->element->description->isRequired()) {
                    $attribs['class'] = 'required';
                }
                echo $this->formLabel($this->element->description->getName(), $this->element->description->getLabel(), $attribs);
                ?>
            </th>
            <td>
                <?php
                echo $this->{$this->element->description->helper}(
                    $this->element->description->getName(),
                    $this->element->description->getValue(),
                    $this->element->description->getAttribs()
                );
                ?>
                <?php if ('<ul class="errors"><li></li></ul>' != ($this->element->description->getMessages())) {
                    echo $this->formErrors($this->element->description->getMessages());
                } ?>
                <div class="hint"><?php echo $this->element->description->getDescription(); ?></div>
            </td>
        </tr>
        <tr>
            <th>&nbsp;</th>
            <td>
                <?php echo $this->{$this->element->submit->helper}(
                    $this->element->submit->getName(),
                    $this->element->submit->getValue(),
                    $this->element->submit->getAttribs()
                );
                ?>
            </td>
        </tr>
    </table>
</form>

<script type="text/javascript">
    $(document).ready(function () {
        $("#<?php echo $this->element->getAttrib('id'); ?>").validationEngine();
    });
</script>