<div class="header">
	<div style="position: relative; width: 147px; height: 125px; float: left;">
		<a style="position: absolute; top: -40px; left: -30px;" href="<?php echo WEBPAGE_ADDRESS;?>/">
			<img src="<?php echo WEBPAGE_ADDRESS;?>/theme/default/images/logo.png" border="0" style=" margin-left:30px; float:left;" alt="Lenjerie de lux" />
		</a>
	</div>
	<div class="right_header">
		<div class="searchForm">
			<?php echo $this->formSearch; ?>
		</div>
		<div class="clear"></div>
	</div>
</div>