<link rel="stylesheet" href="/js/default/nivo-slider-nextgen/themes/default/default.css" type="text/css"
      media="screen"/>
<link rel="stylesheet" href="/js/default/nivo-slider-nextgen/nivo-slider.css" type="text/css" media="screen"/>
<script type="text/javascript" src="/js/default/nivo-slider-nextgen/jquery.nivo.slider.pack.js"></script>
<script type="text/javascript">
    $(window).load(function () {
        $('#slider').nivoSlider({
            effect: '<?php echo $this->slideEffect ? $this->slideEffect : "slideDown";?>', // Specify sets like: 'random,fold,fade,sliceDown'
            slices: 15, // For slice animations
            boxCols: 8, // For box animations
            boxRows: 4, // For box animations
            animSpeed: 1500, // Slide transition speed
            pauseTime: 4500, // How long each slide will show
            startSlide: 0, // Set starting Slide (0 index)
            directionNav: true, // Next & Prev navigation
            directionNavHide: true, // Only show on hover
            controlNav: false, // 1,2,3... navigation
            controlNavThumbs: false, // Use thumbnails for Control Nav
            controlNavThumbsFromRel: false, // Use image rel for thumbs
            controlNavThumbsSearch: '.jpg', // Replace this with...
            controlNavThumbsReplace: '_thumb.jpg', // ...this in thumb Image src
            keyboardNav: true, // Use left & right arrows
            pauseOnHover: true, // Stop animation while hovering
            manualAdvance: false, // Force manual transitions
            captionOpacity: 0.8, // Universal caption opacity
            prevText: 'Prev', // Prev directionNav text
            nextText: 'Next', // Next directionNav text
            beforeChange: function () {
            }, // Triggers before a slide transition
            afterChange: function () {
            }, // Triggers after a slide transition
            slideshowEnd: function () {
            }, // Triggers after all slides have been shown
            lastSlide: function () {
            }, // Triggers when last slide is shown
            afterLoad: function () {
            } // Triggers when slider has loaded
        });
    });
</script>
<style type="text/css">
    #slider {
        position: relative;
        width: 735px; /* Change this to your images width */
        height: 348px; /* Change this to your images height */
        margin: 0px auto;
        background: url(/images/loading.gif) no-repeat 50% 50%;
    }

    #slider img {
        position: absolute;
        top: 0px;
        left: 0px;
        display: none;
    }

    #slider a {
        border: 0;
        display: block;
    }
</style>

<div class="reclama slider-wrapper theme-default">
    <div class="ribbon"></div>
    <div id="slider" class="nivoSlider">
        <?php
        $captions = array();
        if (null != $this->slides) {
            ?>
            <?php
            foreach ($this->slides as $value) {
                ?>
                <a href="<?php echo $value->getUrl() ? $value->getUrl() : ""; ?>">
                    <img src="/media/slides/<?php echo $value->getImage() ? $value->getImage() : ""; ?>"
                         alt="<?php echo $value->getName(); ?>" title=""/>
                </a>
            <?php } ?>
        <?php } ?>
    </div>
</div>