<form method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getAttrib('id');?>" class="<?php echo $this->element->getAttrib('class');?>" enctype="<?php echo $this->element->getEncType();?>">
	<table width="100%" cellpadding="0" cellspacing="5" class="tableAdmin">
		<col width="200" />
		<tr>
			<td colspan="2"><center class="hint"><?php echo Zend_Registry::get('translate')->_("products_add_brands_required"); ?></center></td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td valign="top">
				<?php
					$attribs = array();
					if($this->element->name->isRequired()) {
						$attribs['class'] = 'required';
					}
					echo $this->formLabel($this->element->name->getName(), $this->element->name->getLabel(), $attribs);
				?>
			</td>
			<td>
				<?php
					echo $this->{$this->element->name->helper}
							(
								$this->element->name->getName(),
								$this->element->name->getValue(),
								$this->element->name->getAttribs()
							);
				?>
				<?php if('<ul class="errors"><li></li></ul>' != ($this->element->name->getMessages())) { echo $this->formErrors($this->element->name->getMessages()); } ?>
				<div class="hint"><?php echo $this->element->name->getDescription(); ?></div>
			</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td valign="top">
				<?php
					$attribs = array();
					if($this->element->cpc->isRequired()) {
						$attribs['class'] = 'required';
					}
					echo $this->formLabel($this->element->cpc->getName(), $this->element->cpc->getLabel(), $attribs);
				?>
			</td>
			<td>
				<?php
					echo $this->{$this->element->cpc->helper}
							(
								$this->element->cpc->getName(),
								$this->element->cpc->getValue(),
								$this->element->cpc->getAttribs()
							);
				?>
				<?php if('<ul class="errors"><li></li></ul>' != ($this->element->cpc->getMessages())) { echo $this->formErrors($this->element->cpc->getMessages()); } ?>
				<div class="hint"><?php echo $this->element->cpc->getDescription(); ?></div>
			</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>
				<?php
					echo $this->{$this->element->submit->helper}
							(
								$this->element->submit->getName(),
								$this->element->submit->getValue(),
								$this->element->submit->getAttribs()
							);
				?>
			</td>
		</tr>
	</table>
</form>

<?php $this->headScript()->captureStart() ?>
	$(document).ready(function() {
		$("#<?php echo $this->element->getAttrib('id'); ?>").validationEngine();
	});
<?php $this->headScript()->captureEnd() ?>