<form method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getId();?>" class="<?php echo $this->element->getAttrib('class');?>" enctype="<?php echo $this->element->getEncType();?>">
	<table width="100%" cellpadding="0" cellspacing="0" class="tableAdmin">
		<col width="200" />
		<tr>
			<td colspan="2"><center class="hint"><?php echo Zend_Registry::get('translate')->_('marketing_add_feed_required'); ?></center></td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td valign="top">
				<?php if(null != ($this->element->logo->getValue())) { ?>
				<img src="/media/feeds/<?php echo $this->element->logo->getLogo(); ?>" alt="" />
				<?php } ?>
				<?php
					$attribs = array();
					if($this->element->logo->isRequired()) {
						$attribs['class'] = 'required';
					}
					echo $this->formLabel($this->element->logo->getName(), $this->element->logo->getLabel(), $attribs);
				?>
			</td>
			<td>
				<?php
					echo $this->{$this->element->logo->helper}
							(
								$this->element->logo->getName(),
								$this->element->logo->getValue(),
								$this->element->logo->getAttribs()
							);
				?>
				<?php if('<ul class="errors"><li></li></ul>' != ($this->element->logo->getMessages())) { echo $this->formErrors($this->element->logo->getMessages()); } ?>
				<div class="hint"><?php echo $this->element->logo->getDescription(); ?></div>
				<?php if ($this->element->photo->getValue()) { ?>
				<br />
					<img src="/media/feeds/<?php echo $this->element->photo->getValue(); ?>" alt="" />
				<?php } ?>
			</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td valign="top">
				<?php
					$attribs = array();
					if($this->element->code->isRequired()) {
						$attribs['class'] = 'required';
					}
					echo $this->formLabel($this->element->code->getName(), $this->element->code->getLabel(), $attribs);
				?>
			</td>
			<td>
				<?php
					echo $this->{$this->element->code->helper}
							(
								$this->element->code->getName(),
								$this->element->code->getValue(),
								$this->element->code->getAttribs()
							);
				?>
				<?php if('<ul class="errors"><li></li></ul>' != ($this->element->code->getMessages())) { echo $this->formErrors($this->element->code->getMessages()); } ?>
				<div class="hint"><?php echo $this->element->code->getDescription(); ?></div>
			</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td valign="top">
				<?php
					$attribs = array();
					if($this->element->status->isRequired()) {
						$attribs['class'] = 'required';
					}
					echo $this->formLabel($this->element->status->getName(), $this->element->status->getLabel(), $attribs);
				?>
			</td>
			<td>
				<?php
					echo $this->{$this->element->status->helper}
							(
								$this->element->status->getName(),
								$this->element->status->getValue(),
								$this->element->status->getAttribs(),
								$this->element->status->getMultioptions(),
								'&nbsp;&nbsp;&nbsp;'
							);
				?>
				<?php if('<ul class="errors"><li></li></ul>' != ($this->element->status->getMessages())) { echo $this->formErrors($this->element->status->getMessages()); } ?>
				<div class="hint"><?php echo $this->element->status->getDescription(); ?></div>
			</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>
				<?php
					echo $this->{$this->element->submit->helper}
							(
								$this->element->submit->getName(),
								$this->element->submit->getValue(),
								$this->element->submit->getAttribs()
							);
				?>
			</td>
		</tr>
	</table>
</form>

<?php $this->headScript()->captureStart() ?>
	$(document).ready(function() {
		$("#<?php echo $this->element->getId();?>").validationEngine();
	});
<?php $this->headScript()->captureEnd() ?>