<form method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getId();?>" enctype="<?php echo $this->element->getEncType();?>">
	<div class="regFormWrapper">
		<div class="regSubForm">
			<h3 class="expandable">Send an email</h3>
			<table width="100%" cellpadding="0" cellspacing="5" class="tableAdmin">
			<col width="300" />
				<tr>
					<td colspan="2"><center class="hint">Fields marked with <img src="/images/required.gif" width="10" height="8" border="0" align="absmiddle" /> are required.</center></td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->to->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->to->getName(), $this->element->to->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->to->helper}(
										        $this->element->to->getName(),
										        $this->element->to->getValue(),
										        $this->element->to->getAttribs()
										    );
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->to->getMessages()))){ echo $this->formErrors($this->element->to->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->to->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->emailto->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->emailto->getName(), $this->element->emailto->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->emailto->helper}(
										        $this->element->emailto->getName(),
										        $this->element->emailto->getValue(),
										        $this->element->emailto->getAttribs()
										    );
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->emailto->getMessages()))){ echo $this->formErrors($this->element->emailto->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->emailto->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->subject->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->subject->getName(), $this->element->subject->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->subject->helper}(
										        $this->element->subject->getName(),
										        $this->element->subject->getValue(),
										        $this->element->subject->getAttribs()
										    );
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->subject->getMessages()))){ echo $this->formErrors($this->element->subject->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->subject->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->from->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->from->getName(), $this->element->from->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->from->helper}(
										        $this->element->from->getName(),
										        $this->element->from->getValue(),
										        $this->element->from->getAttribs()
										    );
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->from->getMessages()))){ echo $this->formErrors($this->element->from->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->from->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->emailfrom->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->emailfrom->getName(), $this->element->emailfrom->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->emailfrom->helper}(
										        $this->element->emailfrom->getName(),
										        $this->element->emailfrom->getValue(),
										        $this->element->emailfrom->getAttribs()
										    );
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->emailfrom->getMessages()))){ echo $this->formErrors($this->element->emailfrom->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->emailfrom->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->message->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->message->getName(), $this->element->message->getLabel(), $attribs);?>
					</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td colspan="2">
						<?php
						echo $this->{$this->element->message->helper}(
										        $this->element->message->getName(),
										        $this->element->message->getValue(),
										        $this->element->message->getAttribs()
										    );
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->message->getMessages()))){ echo $this->formErrors($this->element->message->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->message->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">&nbsp;</td>
					<td valign="top">&nbsp;</td>
				</tr>
				<tr>					
					<td colspan="2" align="center">
						<?php
							echo $this->{$this->element->submit->helper}(
											        $this->element->submit->getName(),
											        $this->element->submit->getValue(),
											        $this->element->submit->getAttribs()
											    );
						?>
					</td>
				</tr>
			</table>
		</div>
	</div>
</form>
<?php
	$this->headScript()->appendFile('/js/ckeditor/ckeditor.js');
	echo $this->headScript();
?>
<?php $this->headScript()->captureStart() ?>
	$(document).ready(function() {
		CKEDITOR.replace( 'message',
			{
				width: '600'
			}
		);

		$("#<?php echo $this->element->getAttrib('id');?>").validationEngine();
	});
<?php $this->headScript()->captureEnd() ?>