<style>
    .grid-item { width: 200px;margin: 0 5px 5px 5px;background-color: #ffffff;border-radius: 0 0 5px 5px; }
    .grid-item .image img { border-radius: 5px 5px 0 0; }
    .grid-item .name, .grid-item .price, .grid-item .details { padding:0 10px; }
</style>

<?php
echo '<a href="' . $this->loginUrl . '">Log in with Facebook!</a>';
?>

<?php if ($this->products): ?>
    <div class="grid">
    <?php foreach ($this->products as $product): ?>
        <div class="grid-item">
            <div class="image">
                <img width="200" src="<?php echo WEBPAGE_ADDRESS . '/media/products/shopmania/' . $product->getImageShopmania() ?>" alt="" \>
            </div>
            <div class="name"><?php echo $product->getName() ?></div>
            <div class="price">
                <span class="old"><?php echo $product->getOldprice() ?></span>
                <span class="new"><?php echo $product->getPrice() ?></span>
            </div>
            <div class="details">details</div>
        </div>
    <?php endforeach ?>
    </div>
<?php endif ?>