<?php if (!empty($this->message)) : ?>
    <?php foreach ($this->message as $value) : ?>
        <div class="empty10"></div>
        <?php echo $value; ?>
    <?php endforeach; ?>
<?php endif; ?>

<?php if (null != $this->slideEffect) { ?>
    <div class="empty10"></div>
    <h3>Efecte Slider</h3>
    <form name="frmChangeSlideEffect" action="/admin/settings/slide" method="POST">
        <table width="250" class="tableListingsAll" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th>Efect Activ</th>
                <th>Alte efecte</th>
            </tr>
            <tr>
                <td><?php echo $this->slideEffect->getValue(); ?></td>
                <td align="center">
                    <select name="slideEffectValue" id="slideEffectValue">
                        <?php foreach ($this->slideEffectValues as $value) { ?>
                            <option value="<?php echo $value->getValue(); ?>"><?php echo $value->getValue(); ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td align="center" colspan="2"><input type="submit" value="Modifica"/></td>
            </tr>
        </table>
    </form>
<?php } ?>