<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>lenjerie-de_lux.ro</title>
<link href="/css/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<?php echo $this->render('header.phtml');?>
<div class="container">
	<?php echo $this->render('head.phtml');?>
	<?php echo $this->render('menu.phtml') ?>
	<?php //echo $this->render('slider.phtml') ?>
	<div class="left_col">
	<?php echo $this->layout()->content;?>
	</div>
	<?php echo $this->render('sidebar.phtml') ?>
	<?php echo $this->render('footer.phtml');?>
</div>
</body>
</html>