<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="icon" href="/images/favicon.ico" type="image/x-icon" />
	<title>Lenjerie de lux | Lenjerie | Haine femei | Haine dama | Costum craciunita</title>
	<meta name="description" content="Lenjerie intima, Lenjerie intima de dama oferita de Lenjerie-de-lux.ro contine lenjerie intima,lenjerie de lux , haine femei, haine dama, haine de femei, haine de dama, bluze, pantaloni,corsete, rochite de vara, rochite scurte, rochite sexi,stockings, costume craciunite, lenjerii intime, Costum craciunita, uniforme sexy, babydolls, corsete, costume sexy, costume de baie, Lenjerie intima, Lenjerie sexi, costume de baie, stockings,  uniforme sexy, babydolls, corsete, costume sexy, Craciunite" />
	<meta name="keywords" content="Lenjerie intima, lenjerii intime, lenjerie, Lenjerie de Lux, Costume de baie, haine femei, haine dama, haine de femei, haine de dama, bluze, pantaloni,corsete, rochite de vara, rochite scurte, rochite sexi,  Costume craciunite, Costum craciunita, Lenjerie intima, Lenjerie intima de dama, Rochite, stockings, uniforme sexy, costume sexy, bikini, babydolls, costume de baie, corsete, craciunite" />

    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
    <?php echo $this->headScript(); ?>
</head>
<body>
	<?php echo $this->layout()->content;?>
</div>
</body>
</html>