<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="icon" href="/images/favicon.ico" type="image/x-icon" />
	<?php echo $this->headTitle('Page not found');?>
    <?php echo $this->headLink();?>
    <?php echo $this->headStyle();?>
    <?php echo $this->headScript();?>
</head>
<body>
	<?php echo $this->render('header.phtml');?>

	<div id="content">
		<?php echo $this->layout()->content;?>
	</div>
	<?php echo $this->render('footer.phtml');?>
</body>
</html>