<form method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getId();?>" enctype="<?php echo $this->element->getEncType();?>">
	<div class="regFormWrapper">
		<div class="regSubForm">
			<h3 class="expandable"><?php echo Zend_Registry::get('translate')->_('customers_create_title_customer'); ?></h3>
			<table width="100%" cellpadding="0" cellspacing="5" class="tableAdmin">
			<col width="200" />
				<tr>
					<small class="hint fR">Campurile marcate cu <img src="/images/admin/required.gif" alt="required"/> sunt obligatorii</small>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>				
				<tr>
					<td valign="top">
						<?php 
							$attribs = array();
							if($this->element->password->isRequired()) {
								$attribs['class'] = 'required';
							}
							echo $this->formLabel($this->element->password->getName(), $this->element->password->getLabel(), $attribs);
						?>
					</td>
					<td>
						<?php
							echo $this->{$this->element->password->helper}
									(
										$this->element->password->getName(),
										$this->element->password->getValue(),
										$this->element->password->getAttribs()
									);
						?>
				    	<?php if('<ul class="errors"><li></li></ul>' != ($this->formErrors($this->element->password->getMessages()))) { echo $this->formErrors($this->element->password->getMessages()); } ?>
				    	<p class="description"><?php echo $this->element->password->getDescription(); ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php 
							$attribs = array();
							if($this->element->tbRePassword->isRequired()) {
								$attribs['class'] = 'required';
							}
							echo $this->formLabel($this->element->tbRePassword->getName(), $this->element->tbRePassword->getLabel(), $attribs);
						?>
					</td>
					<td>
						<?php
							echo $this->{$this->element->tbRePassword->helper}
									(
										$this->element->tbRePassword->getName(),
										$this->element->tbRePassword->getValue(),
										$this->element->tbRePassword->getAttribs()
									);
						?>
				    	<?php if('<ul class="errors"><li></li></ul>' != ($this->formErrors($this->element->tbRePassword->getMessages()))) { echo $this->formErrors($this->element->tbRePassword->getMessages()); } ?>
				    	<p class="description"><?php echo $this->element->tbRePassword->getDescription(); ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->email->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->email->getName(), $this->element->email->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->email->helper}(
									$this->element->email->getName(),
									$this->element->email->getValue(),
									$this->element->email->getAttribs()
								);
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->email->getMessages()))){ echo $this->formErrors($this->element->email->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->email->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->tbReEmail->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->tbReEmail->getName(), $this->element->tbReEmail->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->tbReEmail->helper}(
									$this->element->tbReEmail->getName(),
									$this->element->tbReEmail->getValue(),
									$this->element->tbReEmail->getAttribs()
								);
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->tbReEmail->getMessages()))){ echo $this->formErrors($this->element->tbReEmail->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->tbReEmail->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php 
						$attribs = array();
						if ($this->element->status->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->status->getName(), $this->element->status->getLabel(), $attribs); ?>
					</td>
					<td>
						
						<?php
						echo $this->{$this->element->status->helper}(
									$this->element->status->getName(),
									$this->element->status->getValue(),
									$this->element->status->getAttribs(),
									$this->element->status->getMultiOptions(),
									'&nbsp;&nbsp;&nbsp;'
								);
			    		?>
			    		<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->status->getMessages()))){ echo $this->formErrors($this->element->status->getMessages());} ?>
			    		<p class="description"><?php echo $this->element->status->getDescription() ?></p>
					</td>
				</tr>
			</table>
		</div>
		<div class="regSubForm">
			<h3 class="expandable"><?php echo Zend_Registry::get('translate')->_("customers_create_title_basic");?></h3>
			<table width="100%" cellpadding="0" cellspacing="5" class="tableAdmin">
				<col width="200" />
				<tr>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td valign="top">
						&nbsp
					</td>
					<td>
						<?php
							echo $this->{$this->element->person->helper}(
										$this->element->person->getName(),
										$this->element->person->getValue(),
										$this->element->person->getAttribs(),
										$this->element->person->getMultiOptions(),
										'&nbsp;&nbsp;&nbsp;'
									);
						?>
						<?php if('<ul class="errors"><li></li></ul>'!=($this->element->person->getMessages())){ echo  $this->formErrors($this->element->person->getMessages());} ?>
						<div class="hint"><?php echo $this->element->person->getDescription(); ?></div>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->salutation->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->salutation->getName(), $this->element->salutation->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->salutation->helper}(
									$this->element->salutation->getName(),
									$this->element->salutation->getValue(),
									$this->element->salutation->getAttribs(),
									$this->element->salutation->getMultiOptions()
								);
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->salutation->getMessages()))){ echo $this->formErrors($this->element->salutation->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->salutation->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->firstname->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->firstname->getName(), $this->element->firstname->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->firstname->helper}(
									$this->element->firstname->getName(),
									$this->element->firstname->getValue(),
									$this->element->firstname->getAttribs()
								);
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->firstname->getMessages()))){ echo $this->formErrors($this->element->firstname->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->firstname->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->lastname->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->lastname->getName(), $this->element->lastname->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->lastname->helper}(
									$this->element->lastname->getName(),
									$this->element->lastname->getValue(),
									$this->element->lastname->getAttribs()
								);
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->lastname->getMessages()))){ echo $this->formErrors($this->element->lastname->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->lastname->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->cnp->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->cnp->getName(), $this->element->cnp->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->cnp->helper}(
									$this->element->cnp->getName(),
									$this->element->cnp->getValue(),
									$this->element->cnp->getAttribs()
								);
						?>
						<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->cnp->getMessages()))){ echo $this->formErrors($this->element->cnp->getMessages());} ?>
						<p class="description"><small><?php echo $this->element->cnp->getDescription() ?></small></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->seria->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->seria->getName(), $this->element->seria->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->seria->helper}(
									$this->element->seria->getName(),
									$this->element->seria->getValue(),
									$this->element->seria->getAttribs()
								);
						?>
						<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->seria->getMessages()))){ echo $this->formErrors($this->element->seria->getMessages());} ?>
						<p class="description"><small><?php echo $this->element->seria->getDescription() ?></small></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->address->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->address->getName(), $this->element->address->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->address->helper}(
									$this->element->address->getName(),
									$this->element->address->getValue(),
									$this->element->address->getAttribs()
								);
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->address->getMessages()))){ echo $this->formErrors($this->element->address->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->address->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->county->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->county->getName(), $this->element->county->getLabel(), $attribs);?>
					</td>
					<td>
						<div id="suggestCounty">
							<?php
								echo $this->{$this->element->county->helper}(
											$this->element->county->getName(),
											$this->element->county->getValue(),
											$this->element->county->getAttribs()
										);
							?>
							<?php if('<ul class="errors"><li></li></ul>'!=($this->element->county->getMessages())){ echo  $this->formErrors($this->element->county->getMessages());} ?>
							<div class="hint"><?php echo $this->element->county->getDescription(); ?></div>
						</div>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->city->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->city->getName(), $this->element->city->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->city->helper}(
									$this->element->city->getName(),
									$this->element->city->getValue(),
									$this->element->city->getAttribs()
								);
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->city->getMessages()))){ echo $this->formErrors($this->element->city->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->city->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->zip->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->zip->getName(), $this->element->zip->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->zip->helper}(
									$this->element->zip->getName(),
									$this->element->zip->getValue(),
									$this->element->zip->getAttribs()
								);
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->zip->getMessages()))){ echo $this->formErrors($this->element->zip->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->zip->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->phone->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->phone->getName(), $this->element->phone->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
							echo $this->{$this->element->phone->helper}(
										$this->element->phone->getName(),
										$this->element->phone->getValue(),
										$this->element->phone->getAttribs()
									);
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->phone->getMessages()))){ echo $this->formErrors($this->element->phone->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->phone->getDescription() ?></p>
					</td>
				</tr>
<!--				<tr>
					<td valign="top">
						<?php
//							$attribs = array();
//							if($this->element->phone2->isRequired()) {
//								$attribs['class'] = 'required';
//							}
//							echo $this->formLabel($this->element->phone2->getName(), $this->element->phone2->getLabel(), $attribs);
						?>
					</td>
					<td>
						<?php
//							echo $this->{$this->element->phone2->helper}
//									(
//										$this->element->phone2->getName(),
//										$this->element->phone2->getValue(),
//										$this->element->phone2->getAttribs()
//									);
						?>
				    	<?php //if('<ul class="errors"><li></li></ul>' != ($this->formErrors($this->element->phone2->getMessages()))) { echo $this->formErrors($this->element->phone2->getMessages()); } ?>
				    	<p class="description"><?php //echo $this->element->phone2->getDescription() ?></p>
					</td>
				</tr>-->
				<tr>
					<td valign="top">
						<?php
							$attribs = array();
							if($this->element->fax->isRequired()) {
								$attribs['class'] = 'required';
							}
							echo $this->formLabel($this->element->fax->getName(), $this->element->fax->getLabel(), $attribs);
						?>
					</td>
					<td>
						<?php
							echo $this->{$this->element->fax->helper}
									(
										$this->element->fax->getName(),
										$this->element->fax->getValue(),
										$this->element->fax->getAttribs()
									);
						?>
				    	<?php if('<ul class="errors"><li></li></ul>' != ($this->formErrors($this->element->fax->getMessages()))) { echo $this->formErrors($this->element->fax->getMessages()); } ?>
				    	<p class="description"><?php echo $this->element->fax->getDescription() ?></p>
					</td>
				</tr>
			</table>
		</div>
		<span class="insertperson">
			<div id="hiddenperson" class="regSubForm">
				<h3 class="expandable"><?php echo Zend_Registry::get('translate')->_('customers_create_title_company'); ?></h3>
				<table width="100%" cellpadding="0" cellspacing="5" class="tableAdmin">
					<col width="200" />
						<tr>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td valign="top">
								<?php
								$attribs = array();
								if ($this->element->institution->isRequired()) {
									$attribs['class'] = 'required';
								}
								echo $this->formLabel($this->element->institution->getName(), $this->element->institution->getLabel(), $attribs);?>
							</td>
							<td>
								<?php
									echo $this->{$this->element->institution->helper}(
												$this->element->institution->getName(),
												$this->element->institution->getValue(),
												$this->element->institution->getAttribs()
											);
								?>
								<?php if('<ul class="errors"><li></li></ul>'!=($this->element->institution->getMessages())){ echo  $this->formErrors($this->element->institution->getMessages());} ?>
								<div class="hint"><?php echo $this->element->institution->getDescription(); ?></div>
							</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td valign="top">
								<?php
								$attribs = array();
								if ($this->element->fiscalcode->isRequired()) {
									$attribs['class'] = 'required';
								}
								echo $this->formLabel($this->element->fiscalcode->getName(), $this->element->fiscalcode->getLabel(), $attribs);?>
							</td>
							<td>
								<?php
									echo $this->{$this->element->fiscalcode->helper}(
												$this->element->fiscalcode->getName(),
												$this->element->fiscalcode->getValue(),
												$this->element->fiscalcode->getAttribs()
											);
								?>
								<?php if('<ul class="errors"><li></li></ul>'!=($this->element->fiscalcode->getMessages())){ echo  $this->formErrors($this->element->fiscalcode->getMessages());} ?>
								<div class="hint"><?php echo $this->element->fiscalcode->getDescription(); ?></div>
							</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td valign="top">
								<?php
								$attribs = array();
								if ($this->element->traderegister->isRequired()) {
									$attribs['class'] = 'required';
								}
								echo $this->formLabel($this->element->traderegister->getName(), $this->element->traderegister->getLabel(), $attribs);?>
							</td>
							<td>
								<?php
									echo $this->{$this->element->traderegister->helper}(
												$this->element->traderegister->getName(),
												$this->element->traderegister->getValue(),
												$this->element->traderegister->getAttribs()
											);
								?>
								<?php if('<ul class="errors"><li></li></ul>'!=($this->element->traderegister->getMessages())){ echo  $this->formErrors($this->element->traderegister->getMessages());} ?>
								<div class="hint"><?php echo $this->element->traderegister->getDescription(); ?></div>
							</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td valign="top">
								<?php
								$attribs = array();
								if ($this->element->bank->isRequired()) {
									$attribs['class'] = 'required';
								}
								echo $this->formLabel($this->element->bank->getName(), $this->element->bank->getLabel(), $attribs);?>
							</td>
							<td>
								<?php
									echo $this->{$this->element->bank->helper}(
												$this->element->bank->getName(),
												$this->element->bank->getValue(),
												$this->element->bank->getAttribs()
											);
								?>
								<?php if('<ul class="errors"><li></li></ul>'!=($this->element->bank->getMessages())){ echo  $this->formErrors($this->element->bank->getMessages());} ?>
								<div class="hint"><?php echo $this->element->bank->getDescription(); ?></div>
							</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td valign="top">
								<?php
								$attribs = array();
								if ($this->element->ibancode->isRequired()) {
									$attribs['class'] = 'required';
								}
								echo $this->formLabel($this->element->ibancode->getName(), $this->element->ibancode->getLabel(), $attribs);?>
							</td>
							<td>
								<?php
									echo $this->{$this->element->ibancode->helper}(
												$this->element->ibancode->getName(),
												$this->element->ibancode->getValue(),
												$this->element->ibancode->getAttribs()
											);
								?>
								<?php if('<ul class="errors"><li></li></ul>'!=($this->element->ibancode->getMessages())){ echo  $this->formErrors($this->element->ibancode->getMessages());} ?>
								<div class="hint"><?php echo $this->element->ibancode->getDescription(); ?></div>
							</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td valign="top">
								<?php
								$attribs = array();
								if ($this->element->function->isRequired()) {
									$attribs['class'] = 'required';
								}
								echo $this->formLabel($this->element->function->getName(), $this->element->function->getLabel(), $attribs);?>
							</td>
							<td>
								<?php
									echo $this->{$this->element->function->helper}(
												$this->element->function->getName(),
												$this->element->function->getValue(),
												$this->element->function->getAttribs()
											);
								?>
								<?php if('<ul class="errors"><li></li></ul>'!=($this->element->function->getMessages())){ echo  $this->formErrors($this->element->function->getMessages());} ?>
								<div class="hint"><?php echo $this->element->function->getDescription(); ?></div>
							</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td valign="top">
								<?php
								$attribs = array();
								if ($this->element->department->isRequired()) {
									$attribs['class'] = 'required';
								}
								echo $this->formLabel($this->element->department->getName(), $this->element->department->getLabel(), $attribs);?>
							</td>
							<td>
								<?php
									echo $this->{$this->element->department->helper}(
												$this->element->department->getName(),
												$this->element->department->getValue(),
												$this->element->department->getAttribs()
											);
								?>
								<?php if('<ul class="errors"><li></li></ul>'!=($this->element->department->getMessages())){ echo  $this->formErrors($this->element->department->getMessages());} ?>
								<div class="hint"><?php echo $this->element->department->getDescription(); ?></div>
							</td>
						</tr>
				</table>
			</div>
		</span>
		<div class="regSubForm">
			<h3 class="expandable"><?php echo Zend_Registry::get('translate')->_("customers_create_title_contact");?></h3>
			<table width="100%" cellpadding="0" cellspacing="5" class="tableAdmin">
			<col width="200" />
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->addressS->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->addressS->getName(), $this->element->addressS->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->addressS->helper}(
									$this->element->addressS->getName(),
									$this->element->addressS->getValue(),
									$this->element->addressS->getAttribs()
								);
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->addressS->getMessages()))){ echo $this->formErrors($this->element->addressS->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->addressS->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->countyS->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->county->getName(), $this->element->county->getLabel(), $attribs);?>
					</td>
					<td>
						<div id="suggestCounty">
							<?php
								echo $this->{$this->element->countyS->helper}(
											$this->element->countyS->getName(),
											$this->element->countyS->getValue(),
											$this->element->countyS->getAttribs()
										);
							?>
							<?php if('<ul class="errors"><li></li></ul>'!=($this->element->countyS->getMessages())){ echo  $this->formErrors($this->element->countyS->getMessages());} ?>
							<div class="hint"><?php echo $this->element->countyS->getDescription(); ?></div>
							<div class="suggestionsBoxCounty" id="suggestionsCounty" style="display: none;">
								<div class="suggestionList" id="suggestionsListCounty"> &nbsp; </div>
							</div>
						</div>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->cityS->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->cityS->getName(), $this->element->cityS->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->cityS->helper}(
									$this->element->cityS->getName(),
									$this->element->cityS->getValue(),
									$this->element->cityS->getAttribs()
								);
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->cityS->getMessages()))){ echo $this->formErrors($this->element->cityS->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->cityS->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->zipS->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->zipS->getName(), $this->element->zipS->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
						echo $this->{$this->element->zipS->helper}(
									$this->element->zipS->getName(),
									$this->element->zipS->getValue(),
									$this->element->zipS->getAttribs()
								);
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->zipS->getMessages()))){ echo $this->formErrors($this->element->zipS->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->zipS->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">
						<?php
						$attribs = array();
						if ($this->element->phone->isRequired()) {
							$attribs['class'] = 'required';
						}
						echo $this->formLabel($this->element->phoneS->getName(), $this->element->phoneS->getLabel(), $attribs);?>
					</td>
					<td>
						<?php
							echo $this->{$this->element->phoneS->helper}(
										$this->element->phoneS->getName(),
										$this->element->phoneS->getValue(),
										$this->element->phoneS->getAttribs()
									);
						?>
				    	<?php if('<ul class="errors"><li></li></ul>'!=($this->formErrors($this->element->phoneS->getMessages()))){ echo $this->formErrors($this->element->phoneS->getMessages());} ?>
				    	<p class="description"><?php echo $this->element->phoneS->getDescription() ?></p>
					</td>
				</tr>
				<tr>
					<td valign="top">&nbsp;</td>
					<td valign="top">&nbsp;</td>
				<tr>
					<td valign="top">
						&nbsp;
					</td>
					<td>
						<?php
							echo $this->{$this->element->submit->helper}(
										$this->element->submit->getName(),
										$this->element->submit->getValue(),
										$this->element->submit->getAttribs()
									);
						?>
					</td>
				</tr>
			</table>
		</div>
	</div>
</form>
<?php $this->headScript()->captureStart() ?>
	$(document).ready(function() {
		$("#<?php echo $this->element->getId();?>").validationEngine();
	});
<?php $this->headScript()->captureEnd() ?>
<script type="text/javascript">
	$(document).ready(function() {
		var hiddenperson;
		if ($("#person-0").is(":checked")) {
			hiddenperson = $("#hiddenperson").detach();
		}
		$("#person-0").click(function(){
			if ($("#person-0").is(":checked")) {
				hiddenperson = $("#hiddenperson").detach();
			} else if ($("#person-1").is(":checked")) {
				hiddenperson.appendTo('.insertperson');
				hiddenperson = null;
			}
		});
		$("#person-1").click(function(){
			if ($("#person-1").is(":checked")) {
				hiddenperson.appendTo('.insertperson');
				hiddenperson = null;
			} else if ($("#person-0").is(":checked")) {
				hiddenperson = $("#hiddenperson").detach();
			}
		});
	});
</script>
<script type="text/javascript">
	$(document).ready(function() {
		$("#<?php echo $this->element->getId();?>").validationEngine();

//		if($('#country').val()){
//			if($('#city').val()){
//				if($('#country').val().toUpperCase()=='ROMANIA'){
//					shippincity($('#city').val());
//				}else{
//					shippingcountry($('#country').val());
//				}
//			}
//		}
	});

	//	autocopmlete country 1
//	function fill(thisValue) {
//		$('#country').val(thisValue);
//		setTimeout("$('#suggestions').fadeOut();", 200);
//		if(thisValue){
//			if($('#country').val().toUpperCase()=='ROMANIA'){
//				if($('#county').val() && $('#city').val()){
//					shippincity($('#city').val());
//				}
//			}else{
//				shippingcountry(thisValue);
//			}
//		}
//	}

//	$('#country').keyup(
//		function() {
//			if($(this).val() != null){
//				$('#country').addClass('load');
//				$.get("/ajax/countrycomplete/querystring/"+$(this).val(), function(data){
//					if(data){
//						try {
//							var items = eval('(' + data + ')');
//						}  catch (e) {}
//						if(items){
//							$('#suggestions').fadeIn();
//							$('#suggestionsList').html(items);
//							$('#country').removeClass('load');
//						}
//					}
//				});
//			}
//		}
//	);
//	$('#country').blur(
//		function() {
//			fill();
//			if($(this).val()){
//				if($('#country').val().toUpperCase()=='ROMANIA'){
//					if($('#county').val() && $('#city').val()){
//						shippincity($('#city').val());
//					}
//				}else{
//					shippingcountry($(this).val());
//				}
//			}
//		}
//	);

//	autocomplete county 1
//	function fillCounty(thisValue) {
//		$('#county').val(thisValue);
//		setTimeout("$('#suggestionsCounty').fadeOut();", 200);
//	}

//	$('#county').keyup(
//		function() {
//			if($(this).val() != null){
//				$('#county').addClass('load');
//				if($('#country').val().toUpperCase()=='ROMANIA'){
//					$.get("/ajax/countycomplete/querystring/"+$(this).val(), function(data){
//						if(data){
//							try {
//								var items = eval('(' + data + ')');
//							}  catch (e) {}
//							if(items){
//								$('#suggestionsCounty').fadeIn();
//								$('#suggestionsListCounty').html(items);
//								$('#county').removeClass('load');
//							}
//						}
//					});
//				}
//			}
//		}
//	);
//	$('#county').blur(
//		function() {
//			fillCounty();
//		}
//	);

//	autocomplete city 1
//	function fillCity(thisValue) {
//		$('#city').val(thisValue);
//		setTimeout("$('#suggestionsCity').fadeOut();", 200);
//		if(thisValue){
//			shippincity(thisValue);
//		}
//	}

//	$('#city').keyup(
//		function() {
//			if($(this).val() != null){
//				$('#city').addClass('load');
//					$.get("/ajax/citycomplete/querystring/"+$(this).val()+'/county/'+$('#county').val(), function(data){
//						if(data){
//							try {
//								var items = eval('(' + data + ')');
//							}  catch (e) {}
//							if(items){
//								$('#suggestionsCity').fadeIn();
//								$('#suggestionsListCity').html(items);
//								$('#city').removeClass('load');
//							}
//						}
//					});
//			}
//		}
//	);
//	$('#city').blur(
//		function() {
//			fillCity();
//			if($(this).val()){
//				shippincity($(this).val());
//			}
//		}
//	);
</script>