<table>
	<tr>
		<td colspan="2" valign="top">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2" valign="top">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2" valign="top">
			<fieldset style="text-align:left; padding: 8px; border-radius: 5px;">
			<legend><b>Date client</b></legend>
				<table width="100%" cellpadding="0" cellspacing="0">
					<col width="150" />					
					<tr>
						<td>Nume</td>
						<td>= [nume]</td>
					</tr>
					<tr>
						<td>Prenume</td>
						<td>= [prenume]</td>
					</tr>
					<tr>
						<td>Email</td>
						<td>= [email]</td>
					</tr>
					<tr>
						<td>Telefon</td>
						<td>= [telefon]</td>
					</tr>
					<tr>
						<td>Adresa</td>
						<td>= [adresa]</td>
					</tr>
					<tr>
						<td>Judet</td>
						<td>= [judet]</td>
					</tr>
					<tr>
						<td>Oras</td>
						<td>= [oras]</td>
					</tr>
					<tr>
						<td>Cod postal</td>
						<td>= [cod postal]</td>
					</tr>
					<tr>
						<td>Nume (livrare)</td>
						<td>= [numeS]</td>
					</tr>
					<tr>
						<td>Prenume (livrare)</td>
						<td>= [prenumeS]</td>
					</tr>
					<tr>
						<td>Adresa (livrare)</td>
						<td>= [addressS]</td>
					</tr>
					<tr>
						<td>Judet (livrare)</td>
						<td>= [stateS]</td>
					</tr>
					<tr>
						<td>Cod postal (livrare)</td>
						<td>= [zipcodeS]</td>
					</tr>
					<tr>
						<td>Observatii</td>
						<td>= [observatii]</td>
					</tr>

				</table>
			</fieldset>
		</td>		
		<td colspan="2" valign="top">
			<fieldset style="text-align:left; padding: 8px; border-radius: 5px;">
			<legend><b>Date comanda</b></legend>
				<table width="100%" cellpadding="0" cellspacing="0">
					<col width="150" />
					<tr>
						<td>Comanda nr</td>
						<td>= [comanda nr]</td>
					</tr>		
					<tr>
						<td>Cost Total Produse</td>
						<td>= [produse total]</td>
					</tr>
					<tr>
						<td>Cost Livrare</td>
						<td>= [cost livrare]</td>
					</tr>
					<tr>
						<td>Cost Total</td>
						<td>= [total]</td>
					</tr>
					<tr>
						<td>Metoda de plata</td>
						<td>= [metoda de plata]</td>
					</tr>
					<tr>
						<td>Metoda de livrare</td>
						<td>= [metoda de livrare]</td>
					</tr>

					<tr>
						<td>Continut Comanda</td>
						<td>= [continut comanda]</td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
					</tr>					
					<tr>
						<td>Raporteaza</td>
						<td>= [raporteaza]</td>
					</tr>
				</table>
			</fieldset>
		</td>
		<td colspan="2" valign="top">
			<fieldset style="text-align:left; padding: 8px; border-radius: 5px;">
			<legend><b>Date site</b></legend>
				<table width="100%" cellpadding="0" cellspacing="0">
					<col width="150" />
					<tr>
						<td>Nume site</td>
						<td>= [nume site]</td>
					</tr>	
					<tr>
						<td>Telefon</td>
						<td>= [telefon site]</td>
					</tr>
					<tr>
						<td>Telefon 2</td>
						<td>= [telefon site2]</td>
					</tr>
					<tr>
						<td>Email</td>
						<td>= [email site]</td>
					</tr>
					<tr>
						<td>Link</td>
						<td>= [link site]</td>
					</tr>
				</table>	
			</fieldset>
		</td>
	</tr>
</table>