<table>
	<tr>
		<td colspan="2" valign="top">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2" valign="top">
			<fieldset style="text-align:left; padding: 8px; border-radius: 5px;">
			<legend><b><?php echo Zend_Registry::get('translate')->_('template_legend'); ?></b></legend>
				<table width="100%" cellpadding="0" cellspacing="0">
					<col width="200" />
					<tr>
						<td>Email</td>
						<td>= {$email}</td>
					</tr>
					<tr>
						<td><?php echo Zend_Registry::get('translate')->_('template_activation_link'); ?></td>
						<td>= {$activationlink}</td>
					</tr>
					<tr>
						<td><?php echo Zend_Registry::get('translate')->_('template_unsubscribe_link'); ?></td>
						<td>= {$unsubscribelink}</td>
					</tr>
				</table>
			</fieldset>
		</td>
	</tr>
</table>