<?php if (!empty($this->message)) : ?>
    <?php foreach ($this->message as $value) : ?>
        <div class="empty10"></div>
        <?php echo $value; ?>
    <?php endforeach; ?>
<?php endif; ?>

<?php if (null != $this->result) { ?>
    <div class="empty10"></div>
    <table class="tableListingsAll" width="100%" cellspacing="0" cellpadding="0" border="0">
        <col width=""/>
        <col width=""/>
        <col width="120"/>
        <col width="120"/>
        <col width="120"/>
        <tr>
            <th>Nume</th>
            <th>URL</th>
            <th>Nofollow</th>
            <th>Adaugat la</th>
            <th>Optiuni</th>
        </tr>
        <?php foreach ($this->result as $value) { ?>
            <tr>
                <td><?php echo $value->getName(); ?></td>
                <td>
                    <a href="<?php echo $value->getUrl(); ?>" target="_blank"
                       title="<?php echo $value->getName(); ?>"><?php echo $value->getUrl(); ?></a>
                </td>
                <td><?php echo $value->getNofollow(); ?></td>
                <td align="center"><?php echo date('d M, Y', $value->getCreated()); ?></td>
                <td align="center">
                    <a href="/admin/partner/edit/id/<?php echo $value->getId(); ?>" title="Modifica">
                        <img src="/images/admin/icons/edit.png" alt="modifica"/>
                    </a>

                    <a class="confirmDelete" href="/admin/partner/delete/id/<?php echo $value->getId(); ?>"
                       title="Sterge" class="confirmDelete">
                        <img src="/images/admin/icons/delete.png" alt="sterge"/>
                    </a>
                </td>
            </tr>
        <?php } ?>
    </table>

    <!-- BEGIN: Paginare -->
    <?php
    // BEGIN: PAGINATION
    $itemCountPerPage = $this->itemCountPerPage;
    $totalItemCount = $this->totalItemCount;
    if ($itemCountPerPage < $totalItemCount) {
        echo $this->result;
    }
    // END: PAGINATION
    ?>
    <!-- END: Paginare -->
    <div id="confirmDelete" title="<?php echo Zend_Registry::get('translate')->_('confirmation_message'); ?>"
         style="display:none;">
        Sunteti sigur ca doriti sa stergeti acest partener?
    </div>
<?php } else { ?>
    <div class="empty10"></div>
    <div class="mess-false">Nu exista parteneri!</div>
<?php } ?>

<script type="text/javascript">
    $(document).ready(function () {
        $('.confirmDelete').click(function () {
            var link = $(this);
            $("#confirmDelete").dialog({
                bgiframe: true,
                height: 140,
                width: 400,
                modal: true,
                buttons: {
                    '<?php echo Zend_Registry::get('translate')->_('confirmation_yes'); ?>': function () {
                        $(this).dialog('close').dialog('destroy');
                        window.location.href = link.attr('href');
                    },
                    '<?php echo Zend_Registry::get('translate')->_('confirmation_no'); ?>': function () {
                        $(this).dialog('close').dialog('destroy');
                    }
                }
            });
            return false;
        });
    });
</script>