<style type="text/css">

.tableMarimi{

	width: 513px; border-top: 1px solid #676767; border-left: 1px solid #676767;

	margin-top: 10px;

	font-size: 12px;

}

.tableMarimi td{

	padding: 2px;

	border-right: 1px solid #676767; border-bottom: 1px solid #676767;}

.tableMarimi th{

	padding: 2px;

	background-color: #d90867;

	border-right: 1px solid #676767;

	border-bottom: 1px solid #676767;

}

.tableMarimi strong{color: #FFF;}

</style>



<h3>Tabel marimi</h3>

<table class="tableMarimi" cellpadding="0" cellspacing="0" border="0">

	<tbody>

		<tr>

			<th width="66"><div align="left"><strong>Marimea</strong></div></th>

			<th width="117"><div align="center"><strong>Bust</strong></div></th>

			<th width="101" bgcolor="#1D0100"><div align="center"><strong>Marime Cupe</strong></div></th>

			<th width="98" bgcolor="#1D0100"><div align="center"><strong>Talie</strong></div></th>

			<th width="109" bgcolor="#1D0100"><div align="center"><strong>Solduri</strong></div></th>

		</tr>

		<tr>

			<th><div align="left"><strong>S</strong></div></th>

			<td><div align="center">84 - 88 cm</div></td>

			<td><div align="center">A - B</div></td>

			<td><div align="center">60 - 66 cm</div></td>

			<td><div align="center">86 - 91 cm</div></td>

		</tr>

		<tr>

			<th><div align="left"><strong>M</strong></div></th>

			<td><div align="center">89 - 92 cm</div></td>

			<td><div align="center">B</div></td>

			<td><div align="center">67 - 72 cm</div></td>

			<td><div align="center">92 - 96 cm</div></td>

		</tr>

		<tr>

			<th><div align="left"><strong>L</strong></div></th>

			<td><div align="center">93 - 96 cm</div></td>

			<td><div align="center">B - C</div></td>

			<td><div align="center">73 - 78 cm</div></td>

			<td><div align="center">97 - 104 cm</div></td>

		</tr>

		<tr>

			<th><div align="left"><strong>XL</strong></div></th>

			<td><div align="center">97 - 100 cm</div></td>

			<td><div align="center">C - D</div></td>

			<td><div align="center">79 - 82 cm</div></td>

			<td><div align="center">105 - 109 cm</div></td>

		</tr>

		<tr>

			<th><div align="left"><strong>S / M</strong></div></th>

			<td><div align="center">84 - 92 cm</div></td>

			<td><div align="center">A - B</div></td>

			<td><div align="center">60 - 72 cm</div></td>

			<td><div align="center">86 - 96 cm</div></td>

		</tr>

		<tr>

			<th><div align="left"><strong>M / L</strong></div></th>

			<td><div align="center">89 - 96 cm</div></td>

			<td><div align="center">B- C</div></td>

			<td><div align="center">67 - 78 cm</div></td>

			<td> <div align="center">92 - 104 cm</div></td>

		</tr>

		<tr>

			<th><div align="left"><strong>Unica</strong></div></th>

			<td><div align="center">84 - 96 cm</div></td>

			<td><div align="center">A - C</div></td>

			<td><div align="center">60 - 78 cm</div></td>

			<td><div align="center">86 - 104 cm</div></td>

		</tr>

		<tr>

			<th><div align="left"><strong>Queen</strong></div></th>

			<td><div align="center">100 -122 cm</div></td>

			<td><div align="center">D</div></td>

			<td><div align="center">96 -112 cm</div></td>

			<td><div align="center">106 -122 cm</div></td>

		</tr>

	</tbody>

</table>

<img src="/application/sizeinfo.jpg" alt="" style=" float:left;"  /></a>



