<?php echo $this->render('messages.phtml') ?>

<?php if (null != $this->result) { ?>
    <div class="empty10"></div>
    <table class="tableListingsAll" width="100%" cellspacing="0" cellpadding="0" border="0">
        <col width=""/>
        <col width="80"/>
        <tr>
            <th>Nume</th>
            <th>Optiuni</th>
        </tr>
        <?php foreach ($this->result as $value) { ?>
            <tr>
                <td><?php echo $value->getName(); ?></td>
                <td align="center">
                    <a href="/admin/category/edit/id/<?php echo $value->getId(); ?>" title="Modifica">
                        <img src="/images/admin/icons/edit.png" alt="modifica"/>
                    </a>
                    <a class="confirmDelete" href="/admin/category/delete/id/<?php echo $value->getId(); ?>"
                       title="Sterge">
                        <img src="/images/admin/icons/delete.png" alt="sterge"/>
                    </a>
                </td>
            </tr>
            <?php
            $subcategs = getSubcatForCat($value->getId());
            if (!empty($subcategs)) {
                ?>
                <?php foreach ($subcategs as $valuesubcateg) { ?>
                    <tr>
                        <td class="subcategListing"><?php echo $valuesubcateg->getName(); ?></td>
                        <td align="center">
                            <a href="/admin/category/edit/id/<?php echo $valuesubcateg->getId(); ?>" title="Modifica">
                                <img src="/images/admin/icons/edit.png" alt="modifica"/>
                            </a>
                            <a class="confirmDelete"
                               href="/admin/category/delete/id/<?php echo $valuesubcateg->getId(); ?>" title="Sterge">
                                <img src="/images/admin/icons/delete.png" alt="sterge"/>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } ?>
        <?php } ?>
    </table>
    <div id="confirmDelete" title="<?php echo Zend_Registry::get('translate')->_('confirmation_message'); ?>"
         style="display:none;">
        Sunteţi sigur că doriţi să ştergeţi aceasta categorie?
    </div>
<?php } else { ?>
    <div class="empty10"></div>
    <div class="mess-false">Nu exista categorii!</div>
<?php } ?>

<script type="text/javascript">
    $(document).ready(function () {
        $('.confirmDelete').click(function () {
            var link = $(this);
            $("#confirmDelete").dialog({
                bgiframe: true,
                height: 140,
                width: 400,
                modal: true,
                buttons: {
                    '<?php echo Zend_Registry::get('translate')->_('confirmation_yes'); ?>': function () {
                        $(this).dialog('close').dialog('destroy');
                        window.location.href = link.attr('href');
                    },
                    '<?php echo Zend_Registry::get('translate')->_('confirmation_no'); ?>': function () {
                        $(this).dialog('close').dialog('destroy');
                    }
                }
            });
            return false;
        });
    });
</script>