<?php
	$this->headScript()->appendFile('/js/ckeditor/ckeditor.js');
	echo $this->headScript();
?>
<form method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>" id="<?php echo $this->element->getAttrib('id');?>" class="<?php echo $this->element->getAttrib('class');?>">
<table width="100%" cellpadding="0" cellspacing="0">
	<col width="200" />
	<tr>
		<td colspan="2" valign="top">&nbsp;</td>
	</tr>
	<tr>
		<td valign="top">
			<?php
			$attribs = array();
			if ($this->element->subject->isRequired()) {
				$attribs['class'] = 'required';
			}
			echo $this->formLabel($this->element->subject->getName(), $this->element->subject->getLabel(), $attribs);?>
		</td>
		<td>
	    	<?php
	    		echo $this->{$this->element->subject->helper}(
	    					$this->element->subject->getName(),
	    					$this->element->subject->getValue(),
	    					$this->element->subject->getAttribs()
	    				);
	    	?>
	    	<?php echo $this->formErrors($this->element->subject->getMessages()); ?>
			<div class="hint"><?php echo $this->element->subject->getDescription(); ?></div>
		</td>
	</tr>
	<tr>
		<td colspan="2" valign="top">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2">
	    	<?php
	    		echo $this->{$this->element->value->helper}(
	    					$this->element->value->getName(),
	    					$this->element->value->getValue(),
	    					$this->element->value->getAttribs()
	    				);
	    	?>
	    	<?php echo $this->formErrors($this->element->value->getMessages()); ?>
			<div class="hint"><?php echo $this->element->value->getDescription(); ?></div>
		</td>
	</tr>
	<tr>
		<td colspan="2" valign="top">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2">
	    	<?php echo $this->{$this->element->submit->helper}(
	    					$this->element->submit->getName(),
	    					$this->element->submit->getValue(),
	    					$this->element->submit->getAttribs()
	    				);
	    	?>
		</td>
	</tr>
</table>
</form>
<?php $this->headScript()->captureStart() ?>
	$(document).ready(function() {
		$("#<?php echo $this->element->getAttrib('id');?>").validationEngine();
	});
<?php $this->headScript()->captureEnd() ?>

<!--		CKEDITOR.replace( 'value',
			{
				width: '800'
			}

		);-->
