<?php if (!empty($this->message)) : ?>
    <?php foreach ($this->message as $value) : ?>
        <div class="empty10"></div>
        <?php echo $value; ?>
    <?php endforeach; ?>
<?php endif; ?>

<?php if (null != $this->marimi) { ?>
    <div class="empty10"></div>
    <table class="tableListingsAll fL" style="width: 33em;" cellpadding="0" cellspacing="0" border="0">
        <caption>Marimi</caption>
        <col width=""/>
        <col width=""/>
        <col width="120"/>
        <tr>
            <th>Nume</th>
            <th>Nr. Ordine</th>
            <th>Actiuni</th>
        </tr>
        <?php foreach ($this->marimi as $value) { ?>
            <tr>
                <td><?php echo $value->getName(); ?></td>
                <td><?php echo $value->getOrder(); ?></td>
                <td>
                    <a href="/admin/product/editattribute/id/<?php echo $value->getId(); ?>"
                       title="Modifica">Modifica</a>
                    |
                    <a class="confirmDelete" href="/admin/product/deleteattribute/id/<?php echo $value->getId(); ?>"
                       title="Sterge">Sterge</a>
                </td>
            </tr>
        <?php } ?>
    </table>
<?php } ?>

<?php if (null != $this->culori) { ?>
    <table class="tableListingsAll mL20 fL" style="width: 33em;" cellpadding="0" cellspacing="0" border="0">
        <caption>Culori</caption>
        <col width=""/>
        <col width="120"/>
        <tr>
            <th>Nume</th>
            <th>Actiuni</th>
        </tr>
        <?php foreach ($this->culori as $value) { ?>
            <tr>
                <td><?php echo $value->getName(); ?></td>
                <td>
                    <a href="/admin/product/editattribute/id/<?php echo $value->getId(); ?>"
                       title="Modifica">Modifica</a>
                    |
                    <a class="confirmDelete" href="/admin/product/deleteattribute/id/<?php echo $value->getId(); ?>"
                       title="Sterge">Sterge</a>
                </td>
            </tr>
        <?php } ?>
    </table>
    <div id="confirmDelete" title="Mesaj de confirmare" style="display:none;">
        Sunteţi sigur că doriţi să ştergeţi atributul?
    </div>
<?php } ?>

<script type="text/javascript">
    $(document).ready(function () {
        $('.confirmDelete').click(function () {
            var link = $(this);
            $("#confirmDelete").dialog({
                bgiframe: true,
                height: 140,
                width: 400,
                modal: true,
                buttons: {
                    '<?php echo Zend_Registry::get('translate')->_('confirmation_yes'); ?>': function () {
                        $(this).dialog('close').dialog('destroy');
                        window.location.href = link.attr('href');
                    },
                    '<?php echo Zend_Registry::get('translate')->_('confirmation_no'); ?>': function () {
                        $(this).dialog('close').dialog('destroy');
                    }
                }
            });
            return false;
        });
    });
</script>