<div class="empty10"></div>
<div class="fL">
    <a class="button1" href="/admin/product">
        <small>Toate Produsele</small>
    </a>
</div>
<div class="empty10"></div>
<?php if (!empty($this->message)) { ?>
    <?php foreach ($this->message as $value) { ?>
        <div class="empty10"></div>
        <?php echo $value; ?>
    <?php } ?>
<?php } ?>
<div class="empty10"></div>
<?php if (null != $this->result) { ?>
    <div class="empty10"></div>
    <table class="tableListingsAll" width="100%" cellpadding="0" cellspacing="0" border="0">
        <col width=""/>
        <col width="120"/>
        <col width="120"/>
        <col width="120"/>
        <tr>
            <th>Nume</th>
            <th>Pret</th>
            <th>Adaugat la</th>
            <th>Optiuni</th>
        </tr>
        <?php foreach ($this->result as $value) { ?>
            <tr>
                <td><?php echo $value->getName(); ?></td>
                <td align="center"><?php echo $value->getPrice(); ?>
                    <small style="color: #999;">RON</small>
                </td>
                <td align="center"><?php echo date('d M, Y', $value->getCreated()); ?></td>
                <td align="center">
                    <a href="/products/details/id/<?php echo $value->getId(); ?>" target="_blank" title="Vizualizeaza">
                        <img src="/images/admin/icons/display.png" alt="vizualizeaza"/>
                    </a>
                    <a href="/admin/product/edit/id/<?php echo $value->getId(); ?>" title="Modifica">
                        <img src="/images/admin/icons/edit.png" alt="modifica"/>
                    </a>
                    <a class="confirmDelete" href="/admin/product/delete/id/<?php echo $value->getId(); ?>"
                       title="Sterge">
                        <img src="/images/admin/icons/delete.png" alt="sterge"/>
                    </a>
                </td>
            </tr>
        <?php } ?>
    </table>
    <?php
    // BEGIN: PAGINATION
    $itemCountPerPage = $this->itemCountPerPage;
    $totalItemCount = $this->totalItemCount;
    if ($itemCountPerPage < $totalItemCount) {
        echo $this->result;
    }
    // END: PAGINATION
    ?>
<?php } else { ?>
    <div class="empty10"></div>
    <div class="mess-false">Nu exista produse!</div>
<?php } ?>